[2021-08-09 09:08:36] [ERROR] Fail to import application: [django.contrib.admin],due to error: No module named 'django.contrib.admin.api_admin'
[2021-08-09 09:08:36] [ERROR] Fail to import application: [django.contrib.auth],due to error: No module named 'django.contrib.auth.api_admin'
[2021-08-09 09:08:36] [ERROR] Fail to import application: [django.contrib.contenttypes],due to error: No module named 'django.contrib.contenttypes.api_admin'
[2021-08-09 09:08:36] [ERROR] Fail to import application: [django.contrib.sessions],due to error: No module named 'django.contrib.sessions.api_admin'
[2021-08-09 09:08:36] [ERROR] Fail to import application: [django.contrib.messages],due to error: No module named 'django.contrib.messages.api_admin'
[2021-08-09 09:08:36] [ERROR] Fail to import application: [django.contrib.staticfiles],due to error: No module named 'django.contrib.staticfiles.api_admin'
[2021-08-09 09:08:36] [DEBUG] The application and model name are [('api', 'apiproject')]
[2021-08-09 09:08:36] [DEBUG] The application and model name are [('api', 'templates')]
[2021-08-09 09:08:36] [DEBUG] The application and model name are [('api', 'testsuit')]
[2021-08-09 09:08:36] [DEBUG] The application and model name are [('api', 'testcase')]
[2021-08-09 09:08:36] [DEBUG] The application and model name are [('api', 'scenario')]
[2021-08-09 09:08:36] [DEBUG] The application and model name are [('api', 'sql')]
[2021-08-09 09:08:36] [DEBUG] Success to import application :[api]
[2021-08-09 09:08:36] [ERROR] Fail to import application: [backend],due to error: No module named 'backend.api_admin'
[2021-08-09 09:08:36] [ERROR] Fail to import application: [public],due to error: No module named 'public.api_admin'
[2021-08-09 09:08:36] [ERROR] Fail to import application: [django.contrib.admin],due to error: No module named 'django.contrib.admin.public_admin'
[2021-08-09 09:08:36] [ERROR] Fail to import application: [django.contrib.auth],due to error: No module named 'django.contrib.auth.public_admin'
[2021-08-09 09:08:36] [ERROR] Fail to import application: [django.contrib.contenttypes],due to error: No module named 'django.contrib.contenttypes.public_admin'
[2021-08-09 09:08:36] [ERROR] Fail to import application: [django.contrib.sessions],due to error: No module named 'django.contrib.sessions.public_admin'
[2021-08-09 09:08:36] [ERROR] Fail to import application: [django.contrib.messages],due to error: No module named 'django.contrib.messages.public_admin'
[2021-08-09 09:08:36] [ERROR] Fail to import application: [django.contrib.staticfiles],due to error: No module named 'django.contrib.staticfiles.public_admin'
[2021-08-09 09:08:36] [ERROR] Fail to import application: [api],due to error: No module named 'api.public_admin'
[2021-08-09 09:08:36] [ERROR] Fail to import application: [backend],due to error: No module named 'backend.public_admin'
[2021-08-09 09:08:36] [DEBUG] The application and model name are [('public', 'userprofile')]
[2021-08-09 09:08:36] [DEBUG] The application and model name are [('public', 'groups')]
[2021-08-09 09:08:36] [DEBUG] The application and model name are [('public', 'role')]
[2021-08-09 09:08:36] [DEBUG] The application and model name are [('public', 'firstlayermenu')]
[2021-08-09 09:08:36] [DEBUG] The application and model name are [('public', 'submenu')]
[2021-08-09 09:08:36] [DEBUG] The application and model name are [('public', 'businessfunc')]
[2021-08-09 09:08:36] [DEBUG] The application and model name are [('public', 'retrieval')]
[2021-08-09 09:08:36] [DEBUG] The application and model name are [('public', 'resource')]
[2021-08-09 09:08:36] [DEBUG] The application and model name are [('public', 'environment')]
[2021-08-09 09:08:36] [DEBUG] The application and model name are [('public', 'dbinfo')]
[2021-08-09 09:08:36] [DEBUG] The application and model name are [('public', 'logserverinfo')]
[2021-08-09 09:08:36] [DEBUG] The application and model name are [('public', 'configurations')]
[2021-08-09 09:08:36] [DEBUG] The application and model name are [('public', 'cn_en_map')]
[2021-08-09 09:08:36] [DEBUG] The application and model name are [('public', 'steplog')]
[2021-08-09 09:08:36] [DEBUG] The application and model name are [('public', 'todolist')]
[2021-08-09 09:08:36] [DEBUG] Success to import application :[public]
[2021-08-09 09:08:36] [ERROR] Fail to import application: [django.contrib.admin],due to error: No module named 'django.contrib.admin.api_admin'
[2021-08-09 09:08:36] [ERROR] Fail to import application: [django.contrib.auth],due to error: No module named 'django.contrib.auth.api_admin'
[2021-08-09 09:08:36] [ERROR] Fail to import application: [django.contrib.contenttypes],due to error: No module named 'django.contrib.contenttypes.api_admin'
[2021-08-09 09:08:36] [ERROR] Fail to import application: [django.contrib.sessions],due to error: No module named 'django.contrib.sessions.api_admin'
[2021-08-09 09:08:36] [ERROR] Fail to import application: [django.contrib.messages],due to error: No module named 'django.contrib.messages.api_admin'
[2021-08-09 09:08:36] [ERROR] Fail to import application: [django.contrib.staticfiles],due to error: No module named 'django.contrib.staticfiles.api_admin'
[2021-08-09 09:08:36] [DEBUG] Success to import application :[api]
[2021-08-09 09:08:36] [ERROR] Fail to import application: [backend],due to error: No module named 'backend.api_admin'
[2021-08-09 09:08:36] [ERROR] Fail to import application: [public],due to error: No module named 'public.api_admin'
[2021-08-09 09:08:36] [ERROR] Fail to import application: [django.contrib.admin],due to error: No module named 'django.contrib.admin.web_admin'
[2021-08-09 09:08:36] [ERROR] Fail to import application: [django.contrib.auth],due to error: No module named 'django.contrib.auth.web_admin'
[2021-08-09 09:08:36] [ERROR] Fail to import application: [django.contrib.contenttypes],due to error: No module named 'django.contrib.contenttypes.web_admin'
[2021-08-09 09:08:36] [ERROR] Fail to import application: [django.contrib.sessions],due to error: No module named 'django.contrib.sessions.web_admin'
[2021-08-09 09:08:36] [ERROR] Fail to import application: [django.contrib.messages],due to error: No module named 'django.contrib.messages.web_admin'
[2021-08-09 09:08:36] [ERROR] Fail to import application: [django.contrib.staticfiles],due to error: No module named 'django.contrib.staticfiles.web_admin'
[2021-08-09 09:08:36] [ERROR] Fail to import application: [api],due to error: No module named 'api.web_admin'
[2021-08-09 09:08:36] [ERROR] Fail to import application: [backend],due to error: No module named 'backend.web_admin'
[2021-08-09 09:08:36] [ERROR] Fail to import application: [public],due to error: No module named 'public.web_admin'
[2021-08-09 09:17:06] [DEBUG] Start to match permission: <class 'tuple'>
[2021-08-09 09:17:06] [INFO] The user is Administrator!
[2021-08-09 09:17:06] [DEBUG] Prepare to execute: delete_selected!
[2021-08-09 09:17:06] [DEBUG] Prepare to execute: valid_selected!
[2021-08-09 09:17:06] [DEBUG] Prepare to execute: invalid_selected!
[2021-08-09 09:17:06] [ERROR] Fail to display the field :[execute]
[2021-08-09 09:17:06] [ERROR] Fail to display the field :[expand]
[2021-08-09 09:17:06] [ERROR] Fail to display the field :[execute]
[2021-08-09 09:17:06] [ERROR] Fail to display the field :[expand]
[2021-08-09 09:17:12] [DEBUG] Start to match permission: <class 'tuple'>
[2021-08-09 09:17:12] [INFO] The user is Administrator!
[2021-08-09 09:17:12] [DEBUG] Prepare to execute: delete_selected!
[2021-08-09 09:17:12] [DEBUG] Prepare to execute: valid_selected!
[2021-08-09 09:17:12] [DEBUG] Prepare to execute: invalid_selected!
[2021-08-09 09:17:12] [ERROR] Fail to display the field :[execute]
[2021-08-09 09:17:12] [ERROR] Fail to display the field :[expand]
[2021-08-09 09:17:12] [ERROR] Fail to display the field :[execute]
[2021-08-09 09:17:12] [ERROR] Fail to display the field :[expand]
[2021-08-09 09:30:12] [DEBUG] Start to match permission: <class 'tuple'>
[2021-08-09 09:30:12] [INFO] The user is Administrator!
[2021-08-09 09:30:12] [DEBUG] Prepare to execute: delete_selected!
[2021-08-09 09:30:12] [DEBUG] Prepare to execute: valid_selected!
[2021-08-09 09:30:12] [DEBUG] Prepare to execute: invalid_selected!
[2021-08-09 09:30:12] [ERROR] Fail to display the field :[expand]
[2021-08-09 09:30:12] [ERROR] Fail to display the field :[expand]
[2021-08-09 13:41:58] [ERROR] Fail to import application: [django.contrib.admin],due to error: No module named 'django.contrib.admin.api_admin'
[2021-08-09 13:41:58] [ERROR] Fail to import application: [django.contrib.auth],due to error: No module named 'django.contrib.auth.api_admin'
[2021-08-09 13:41:58] [ERROR] Fail to import application: [django.contrib.contenttypes],due to error: No module named 'django.contrib.contenttypes.api_admin'
[2021-08-09 13:41:58] [ERROR] Fail to import application: [django.contrib.sessions],due to error: No module named 'django.contrib.sessions.api_admin'
[2021-08-09 13:41:58] [ERROR] Fail to import application: [django.contrib.messages],due to error: No module named 'django.contrib.messages.api_admin'
[2021-08-09 13:41:58] [ERROR] Fail to import application: [django.contrib.staticfiles],due to error: No module named 'django.contrib.staticfiles.api_admin'
[2021-08-09 13:41:58] [DEBUG] The application and model name are [('api', 'apiproject')]
[2021-08-09 13:41:58] [DEBUG] The application and model name are [('api', 'templates')]
[2021-08-09 13:41:58] [DEBUG] The application and model name are [('api', 'testsuit')]
[2021-08-09 13:41:58] [DEBUG] The application and model name are [('api', 'testcase')]
[2021-08-09 13:41:58] [DEBUG] The application and model name are [('api', 'scenario')]
[2021-08-09 13:41:58] [DEBUG] The application and model name are [('api', 'sql')]
[2021-08-09 13:41:58] [DEBUG] Success to import application :[api]
[2021-08-09 13:41:58] [ERROR] Fail to import application: [backend],due to error: No module named 'backend.api_admin'
[2021-08-09 13:41:58] [ERROR] Fail to import application: [public],due to error: No module named 'public.api_admin'
[2021-08-09 13:41:58] [ERROR] Fail to import application: [django.contrib.admin],due to error: No module named 'django.contrib.admin.public_admin'
[2021-08-09 13:41:58] [ERROR] Fail to import application: [django.contrib.auth],due to error: No module named 'django.contrib.auth.public_admin'
[2021-08-09 13:41:58] [ERROR] Fail to import application: [django.contrib.contenttypes],due to error: No module named 'django.contrib.contenttypes.public_admin'
[2021-08-09 13:41:58] [ERROR] Fail to import application: [django.contrib.sessions],due to error: No module named 'django.contrib.sessions.public_admin'
[2021-08-09 13:41:58] [ERROR] Fail to import application: [django.contrib.messages],due to error: No module named 'django.contrib.messages.public_admin'
[2021-08-09 13:41:58] [ERROR] Fail to import application: [django.contrib.staticfiles],due to error: No module named 'django.contrib.staticfiles.public_admin'
[2021-08-09 13:41:58] [ERROR] Fail to import application: [api],due to error: No module named 'api.public_admin'
[2021-08-09 13:41:58] [ERROR] Fail to import application: [backend],due to error: No module named 'backend.public_admin'
[2021-08-09 13:41:58] [DEBUG] The application and model name are [('public', 'userprofile')]
[2021-08-09 13:41:58] [DEBUG] The application and model name are [('public', 'groups')]
[2021-08-09 13:41:58] [DEBUG] The application and model name are [('public', 'role')]
[2021-08-09 13:41:58] [DEBUG] The application and model name are [('public', 'firstlayermenu')]
[2021-08-09 13:41:58] [DEBUG] The application and model name are [('public', 'submenu')]
[2021-08-09 13:41:58] [DEBUG] The application and model name are [('public', 'businessfunc')]
[2021-08-09 13:41:58] [DEBUG] The application and model name are [('public', 'retrieval')]
[2021-08-09 13:41:58] [DEBUG] The application and model name are [('public', 'resource')]
[2021-08-09 13:41:58] [DEBUG] The application and model name are [('public', 'environment')]
[2021-08-09 13:41:58] [DEBUG] The application and model name are [('public', 'dbinfo')]
[2021-08-09 13:41:58] [DEBUG] The application and model name are [('public', 'logserverinfo')]
[2021-08-09 13:41:58] [DEBUG] The application and model name are [('public', 'configurations')]
[2021-08-09 13:41:58] [DEBUG] The application and model name are [('public', 'cn_en_map')]
[2021-08-09 13:41:58] [DEBUG] The application and model name are [('public', 'steplog')]
[2021-08-09 13:41:58] [DEBUG] The application and model name are [('public', 'todolist')]
[2021-08-09 13:41:58] [DEBUG] Success to import application :[public]
[2021-08-09 13:41:58] [ERROR] Fail to import application: [django.contrib.admin],due to error: No module named 'django.contrib.admin.api_admin'
[2021-08-09 13:41:58] [ERROR] Fail to import application: [django.contrib.auth],due to error: No module named 'django.contrib.auth.api_admin'
[2021-08-09 13:41:58] [ERROR] Fail to import application: [django.contrib.contenttypes],due to error: No module named 'django.contrib.contenttypes.api_admin'
[2021-08-09 13:41:58] [ERROR] Fail to import application: [django.contrib.sessions],due to error: No module named 'django.contrib.sessions.api_admin'
[2021-08-09 13:41:58] [ERROR] Fail to import application: [django.contrib.messages],due to error: No module named 'django.contrib.messages.api_admin'
[2021-08-09 13:41:58] [ERROR] Fail to import application: [django.contrib.staticfiles],due to error: No module named 'django.contrib.staticfiles.api_admin'
[2021-08-09 13:41:58] [DEBUG] Success to import application :[api]
[2021-08-09 13:41:58] [ERROR] Fail to import application: [backend],due to error: No module named 'backend.api_admin'
[2021-08-09 13:41:58] [ERROR] Fail to import application: [public],due to error: No module named 'public.api_admin'
[2021-08-09 13:41:58] [ERROR] Fail to import application: [django.contrib.admin],due to error: No module named 'django.contrib.admin.web_admin'
[2021-08-09 13:41:58] [ERROR] Fail to import application: [django.contrib.auth],due to error: No module named 'django.contrib.auth.web_admin'
[2021-08-09 13:41:58] [ERROR] Fail to import application: [django.contrib.contenttypes],due to error: No module named 'django.contrib.contenttypes.web_admin'
[2021-08-09 13:41:58] [ERROR] Fail to import application: [django.contrib.sessions],due to error: No module named 'django.contrib.sessions.web_admin'
[2021-08-09 13:41:58] [ERROR] Fail to import application: [django.contrib.messages],due to error: No module named 'django.contrib.messages.web_admin'
[2021-08-09 13:41:58] [ERROR] Fail to import application: [django.contrib.staticfiles],due to error: No module named 'django.contrib.staticfiles.web_admin'
[2021-08-09 13:41:58] [ERROR] Fail to import application: [api],due to error: No module named 'api.web_admin'
[2021-08-09 13:41:58] [ERROR] Fail to import application: [backend],due to error: No module named 'backend.web_admin'
[2021-08-09 13:41:58] [ERROR] Fail to import application: [public],due to error: No module named 'public.web_admin'
[2021-08-09 13:43:09] [ERROR] Fail to import application: [django.contrib.admin],due to error: No module named 'django.contrib.admin.api_admin'
[2021-08-09 13:43:09] [ERROR] Fail to import application: [django.contrib.auth],due to error: No module named 'django.contrib.auth.api_admin'
[2021-08-09 13:43:09] [ERROR] Fail to import application: [django.contrib.contenttypes],due to error: No module named 'django.contrib.contenttypes.api_admin'
[2021-08-09 13:43:09] [ERROR] Fail to import application: [django.contrib.sessions],due to error: No module named 'django.contrib.sessions.api_admin'
[2021-08-09 13:43:09] [ERROR] Fail to import application: [django.contrib.messages],due to error: No module named 'django.contrib.messages.api_admin'
[2021-08-09 13:43:09] [ERROR] Fail to import application: [django.contrib.staticfiles],due to error: No module named 'django.contrib.staticfiles.api_admin'
[2021-08-09 13:43:09] [DEBUG] The application and model name are [('api', 'apiproject')]
[2021-08-09 13:43:09] [DEBUG] The application and model name are [('api', 'templates')]
[2021-08-09 13:43:09] [DEBUG] The application and model name are [('api', 'testsuit')]
[2021-08-09 13:43:09] [DEBUG] The application and model name are [('api', 'testcase')]
[2021-08-09 13:43:09] [DEBUG] The application and model name are [('api', 'scenario')]
[2021-08-09 13:43:09] [DEBUG] The application and model name are [('api', 'sql')]
[2021-08-09 13:43:09] [DEBUG] Success to import application :[api]
[2021-08-09 13:43:09] [ERROR] Fail to import application: [backend],due to error: No module named 'backend.api_admin'
[2021-08-09 13:43:09] [ERROR] Fail to import application: [public],due to error: No module named 'public.api_admin'
[2021-08-09 13:43:09] [ERROR] Fail to import application: [django.contrib.admin],due to error: No module named 'django.contrib.admin.public_admin'
[2021-08-09 13:43:09] [ERROR] Fail to import application: [django.contrib.auth],due to error: No module named 'django.contrib.auth.public_admin'
[2021-08-09 13:43:09] [ERROR] Fail to import application: [django.contrib.contenttypes],due to error: No module named 'django.contrib.contenttypes.public_admin'
[2021-08-09 13:43:09] [ERROR] Fail to import application: [django.contrib.sessions],due to error: No module named 'django.contrib.sessions.public_admin'
[2021-08-09 13:43:09] [ERROR] Fail to import application: [django.contrib.messages],due to error: No module named 'django.contrib.messages.public_admin'
[2021-08-09 13:43:09] [ERROR] Fail to import application: [django.contrib.staticfiles],due to error: No module named 'django.contrib.staticfiles.public_admin'
[2021-08-09 13:43:09] [ERROR] Fail to import application: [api],due to error: No module named 'api.public_admin'
[2021-08-09 13:43:09] [ERROR] Fail to import application: [backend],due to error: No module named 'backend.public_admin'
[2021-08-09 13:43:09] [DEBUG] The application and model name are [('public', 'userprofile')]
[2021-08-09 13:43:09] [DEBUG] The application and model name are [('public', 'groups')]
[2021-08-09 13:43:09] [DEBUG] The application and model name are [('public', 'role')]
[2021-08-09 13:43:09] [DEBUG] The application and model name are [('public', 'firstlayermenu')]
[2021-08-09 13:43:09] [DEBUG] The application and model name are [('public', 'submenu')]
[2021-08-09 13:43:09] [DEBUG] The application and model name are [('public', 'businessfunc')]
[2021-08-09 13:43:09] [DEBUG] The application and model name are [('public', 'retrieval')]
[2021-08-09 13:43:09] [DEBUG] The application and model name are [('public', 'resource')]
[2021-08-09 13:43:09] [DEBUG] The application and model name are [('public', 'environment')]
[2021-08-09 13:43:09] [DEBUG] The application and model name are [('public', 'dbinfo')]
[2021-08-09 13:43:09] [DEBUG] The application and model name are [('public', 'logserverinfo')]
[2021-08-09 13:43:09] [DEBUG] The application and model name are [('public', 'configurations')]
[2021-08-09 13:43:09] [DEBUG] The application and model name are [('public', 'cn_en_map')]
[2021-08-09 13:43:09] [DEBUG] The application and model name are [('public', 'steplog')]
[2021-08-09 13:43:09] [DEBUG] The application and model name are [('public', 'todolist')]
[2021-08-09 13:43:09] [DEBUG] Success to import application :[public]
[2021-08-09 13:43:09] [ERROR] Fail to import application: [django.contrib.admin],due to error: No module named 'django.contrib.admin.api_admin'
[2021-08-09 13:43:09] [ERROR] Fail to import application: [django.contrib.auth],due to error: No module named 'django.contrib.auth.api_admin'
[2021-08-09 13:43:09] [ERROR] Fail to import application: [django.contrib.contenttypes],due to error: No module named 'django.contrib.contenttypes.api_admin'
[2021-08-09 13:43:09] [ERROR] Fail to import application: [django.contrib.sessions],due to error: No module named 'django.contrib.sessions.api_admin'
[2021-08-09 13:43:09] [ERROR] Fail to import application: [django.contrib.messages],due to error: No module named 'django.contrib.messages.api_admin'
[2021-08-09 13:43:09] [ERROR] Fail to import application: [django.contrib.staticfiles],due to error: No module named 'django.contrib.staticfiles.api_admin'
[2021-08-09 13:43:09] [DEBUG] Success to import application :[api]
[2021-08-09 13:43:09] [ERROR] Fail to import application: [backend],due to error: No module named 'backend.api_admin'
[2021-08-09 13:43:09] [ERROR] Fail to import application: [public],due to error: No module named 'public.api_admin'
[2021-08-09 13:43:09] [ERROR] Fail to import application: [django.contrib.admin],due to error: No module named 'django.contrib.admin.web_admin'
[2021-08-09 13:43:09] [ERROR] Fail to import application: [django.contrib.auth],due to error: No module named 'django.contrib.auth.web_admin'
[2021-08-09 13:43:09] [ERROR] Fail to import application: [django.contrib.contenttypes],due to error: No module named 'django.contrib.contenttypes.web_admin'
[2021-08-09 13:43:09] [ERROR] Fail to import application: [django.contrib.sessions],due to error: No module named 'django.contrib.sessions.web_admin'
[2021-08-09 13:43:09] [ERROR] Fail to import application: [django.contrib.messages],due to error: No module named 'django.contrib.messages.web_admin'
[2021-08-09 13:43:09] [ERROR] Fail to import application: [django.contrib.staticfiles],due to error: No module named 'django.contrib.staticfiles.web_admin'
[2021-08-09 13:43:09] [ERROR] Fail to import application: [api],due to error: No module named 'api.web_admin'
[2021-08-09 13:43:09] [ERROR] Fail to import application: [backend],due to error: No module named 'backend.web_admin'
[2021-08-09 13:43:09] [ERROR] Fail to import application: [public],due to error: No module named 'public.web_admin'
[2021-08-09 13:46:55] [DEBUG] Start to match permission: <class 'tuple'>
[2021-08-09 13:46:55] [DEBUG] The logined user is:{request.user,} and the current url is: {current_url_name}
[2021-08-09 13:46:55] [DEBUG] The permission list is: {permission_list}
[2021-08-09 13:46:55] [DEBUG] The permission group is: <QuerySet [('web_table_data',), ('web_table_update_view',), ('web_table_update',), ('web_table_add',), ('web_table_add_view',), ('web_table_delete_view',), ('password_reset_get',)]>
[2021-08-09 13:46:55] [DEBUG] The matched result is: [True, True, True]
[2021-08-09 13:46:55] [DEBUG] The permission name is: web_table_data and permissions are:[True, True, True]
[2021-08-09 13:46:55] [INFO] Splite the permission: f('web', 'table', 'data')
[2021-08-09 13:46:55] [DEBUG] Create permission: {perm_obj}
[2021-08-09 13:46:55] [INFO] The user have the permission!
[2021-08-09 13:46:55] [DEBUG] Prepare to execute: delete_selected!
[2021-08-09 13:46:55] [DEBUG] Prepare to execute: valid_selected!
[2021-08-09 13:46:55] [DEBUG] Prepare to execute: invalid_selected!
[2021-08-09 13:46:55] [DEBUG] The user have access: <HttpResponse status_code=200, "text/html; charset=utf-8"> to get the page!
[2021-08-09 13:46:56] [DEBUG] Prepare to execute: delete_selected!
[2021-08-09 13:46:56] [DEBUG] Prepare to execute: valid_selected!
[2021-08-09 13:46:56] [DEBUG] Prepare to execute: invalid_selected!
[2021-08-09 13:46:58] [DEBUG] Start to match permission: <class 'tuple'>
[2021-08-09 13:46:58] [DEBUG] The logined user is:{request.user,} and the current url is: {current_url_name}
[2021-08-09 13:46:58] [DEBUG] The permission list is: {permission_list}
[2021-08-09 13:46:58] [DEBUG] The permission group is: <QuerySet [('web_table_data',), ('web_table_update_view',), ('web_table_update',), ('web_table_add',), ('web_table_add_view',), ('web_table_delete_view',), ('password_reset_get',)]>
[2021-08-09 13:46:58] [DEBUG] The matched result is: [True, True, True]
[2021-08-09 13:46:58] [DEBUG] The permission name is: web_table_update_view and permissions are:[True, True, True]
[2021-08-09 13:46:58] [INFO] Splite the permission: f('web', 'table', 'update', 'view')
[2021-08-09 13:46:58] [DEBUG] Create permission: {perm_obj}
[2021-08-09 13:46:58] [INFO] The user have the permission!
[2021-08-09 13:46:58] [DEBUG] The user have access: <HttpResponse status_code=200, "text/html; charset=utf-8"> to get the page!
[2021-08-09 13:47:12] [DEBUG] Start to match permission: <class 'tuple'>
[2021-08-09 13:47:12] [DEBUG] The logined user is:{request.user,} and the current url is: {current_url_name}
[2021-08-09 13:47:12] [DEBUG] The permission list is: {permission_list}
[2021-08-09 13:47:12] [DEBUG] The permission group is: <QuerySet [('web_table_data',), ('web_table_update_view',), ('web_table_update',), ('web_table_add',), ('web_table_add_view',), ('web_table_delete_view',), ('password_reset_get',)]>
[2021-08-09 13:47:12] [DEBUG] The matched result is: [True, True, True]
[2021-08-09 13:47:12] [DEBUG] The permission name is: web_table_data and permissions are:[True, True, True]
[2021-08-09 13:47:12] [INFO] Splite the permission: f('web', 'table', 'data')
[2021-08-09 13:47:12] [DEBUG] Create permission: {perm_obj}
[2021-08-09 13:47:12] [INFO] The user have the permission!
[2021-08-09 13:47:12] [DEBUG] Prepare to execute: delete_selected!
[2021-08-09 13:47:12] [DEBUG] Prepare to execute: valid_selected!
[2021-08-09 13:47:12] [DEBUG] Prepare to execute: invalid_selected!
[2021-08-09 13:47:12] [DEBUG] The user have access: <HttpResponse status_code=200, "text/html; charset=utf-8"> to get the page!
[2021-08-09 13:47:12] [DEBUG] Prepare to execute: delete_selected!
[2021-08-09 13:47:12] [DEBUG] Prepare to execute: valid_selected!
[2021-08-09 13:47:12] [DEBUG] Prepare to execute: invalid_selected!
[2021-08-09 15:37:42] [DEBUG] Start to match permission: <class 'tuple'>
[2021-08-09 15:37:42] [DEBUG] The logined user is:{request.user,} and the current url is: {current_url_name}
[2021-08-09 15:37:42] [DEBUG] The permission list is: {permission_list}
[2021-08-09 15:37:42] [DEBUG] The permission group is: <QuerySet [('web_table_data',), ('web_table_update_view',), ('web_table_update',), ('web_table_add',), ('web_table_add_view',), ('web_table_delete_view',), ('password_reset_get',)]>
[2021-08-09 15:37:42] [DEBUG] The matched result is: [True, True, True]
[2021-08-09 15:37:42] [DEBUG] The permission name is: web_table_update_view and permissions are:[True, True, True]
[2021-08-09 15:37:42] [INFO] Splite the permission: f('web', 'table', 'update', 'view')
[2021-08-09 15:37:42] [DEBUG] Create permission: {perm_obj}
[2021-08-09 15:37:42] [INFO] The user have the permission!
[2021-08-09 15:37:42] [DEBUG] The user have access: <HttpResponse status_code=200, "text/html; charset=utf-8"> to get the page!
[2021-08-09 15:37:53] [DEBUG] Start to match permission: <class 'tuple'>
[2021-08-09 15:37:53] [DEBUG] The logined user is:{request.user,} and the current url is: {current_url_name}
[2021-08-09 15:37:53] [DEBUG] The permission list is: {permission_list}
[2021-08-09 15:37:53] [DEBUG] The permission group is: <QuerySet [('web_table_data',), ('web_table_update_view',), ('web_table_update',), ('web_table_add',), ('web_table_add_view',), ('web_table_delete_view',), ('password_reset_get',)]>
[2021-08-09 15:37:53] [DEBUG] The matched result is: [True, True, True]
[2021-08-09 15:37:53] [DEBUG] The permission name is: web_table_data and permissions are:[True, True, True]
[2021-08-09 15:37:53] [INFO] Splite the permission: f('web', 'table', 'data')
[2021-08-09 15:37:53] [DEBUG] Create permission: {perm_obj}
[2021-08-09 15:37:53] [INFO] The user have the permission!
[2021-08-09 15:37:53] [DEBUG] Prepare to execute: delete_selected!
[2021-08-09 15:37:53] [DEBUG] Prepare to execute: valid_selected!
[2021-08-09 15:37:53] [DEBUG] Prepare to execute: invalid_selected!
[2021-08-09 15:37:53] [DEBUG] The user have access: <HttpResponse status_code=200, "text/html; charset=utf-8"> to get the page!
[2021-08-09 15:37:53] [DEBUG] Prepare to execute: delete_selected!
[2021-08-09 15:37:53] [DEBUG] Prepare to execute: valid_selected!
[2021-08-09 15:37:53] [DEBUG] Prepare to execute: invalid_selected!
[2021-08-09 17:01:17] [DEBUG] Start to match permission: <class 'tuple'>
[2021-08-09 17:01:17] [DEBUG] The logined user is:{request.user,} and the current url is: {current_url_name}
[2021-08-09 17:01:17] [DEBUG] The permission list is: {permission_list}
[2021-08-09 17:01:17] [DEBUG] The permission group is: <QuerySet [('web_table_data',), ('web_table_update_view',), ('web_table_update',), ('web_table_add',), ('web_table_add_view',), ('web_table_delete_view',), ('password_reset_get',)]>
[2021-08-09 17:01:17] [DEBUG] The matched result is: [True, True, True]
[2021-08-09 17:01:17] [DEBUG] The permission name is: web_table_data and permissions are:[True, True, True]
[2021-08-09 17:01:17] [INFO] Splite the permission: f('web', 'table', 'data')
[2021-08-09 17:01:17] [DEBUG] Create permission: {perm_obj}
[2021-08-09 17:01:17] [INFO] The user have the permission!
[2021-08-09 17:01:18] [DEBUG] Prepare to execute: delete_selected!
[2021-08-09 17:01:18] [DEBUG] Prepare to execute: valid_selected!
[2021-08-09 17:01:18] [DEBUG] Prepare to execute: invalid_selected!
[2021-08-09 17:01:18] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:01:18] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:01:18] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:01:18] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:01:18] [DEBUG] The user have access: <HttpResponse status_code=200, "text/html; charset=utf-8"> to get the page!
[2021-08-09 17:01:18] [DEBUG] Prepare to execute: delete_selected!
[2021-08-09 17:01:18] [DEBUG] Prepare to execute: valid_selected!
[2021-08-09 17:01:18] [DEBUG] Prepare to execute: invalid_selected!
[2021-08-09 17:01:18] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:01:18] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:01:18] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:01:18] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:03:58] [ERROR] Fail to import application: [django.contrib.admin],due to error: No module named 'django.contrib.admin.api_admin'
[2021-08-09 17:03:58] [ERROR] Fail to import application: [django.contrib.auth],due to error: No module named 'django.contrib.auth.api_admin'
[2021-08-09 17:03:58] [ERROR] Fail to import application: [django.contrib.contenttypes],due to error: No module named 'django.contrib.contenttypes.api_admin'
[2021-08-09 17:03:58] [ERROR] Fail to import application: [django.contrib.sessions],due to error: No module named 'django.contrib.sessions.api_admin'
[2021-08-09 17:03:58] [ERROR] Fail to import application: [django.contrib.messages],due to error: No module named 'django.contrib.messages.api_admin'
[2021-08-09 17:03:58] [ERROR] Fail to import application: [django.contrib.staticfiles],due to error: No module named 'django.contrib.staticfiles.api_admin'
[2021-08-09 17:03:58] [DEBUG] The application and model name are [('api', 'apiproject')]
[2021-08-09 17:03:58] [DEBUG] The application and model name are [('api', 'templates')]
[2021-08-09 17:03:58] [DEBUG] The application and model name are [('api', 'testsuit')]
[2021-08-09 17:03:58] [DEBUG] The application and model name are [('api', 'testcase')]
[2021-08-09 17:03:58] [DEBUG] The application and model name are [('api', 'scenario')]
[2021-08-09 17:03:58] [DEBUG] The application and model name are [('api', 'sql')]
[2021-08-09 17:03:58] [DEBUG] Success to import application :[api]
[2021-08-09 17:03:58] [ERROR] Fail to import application: [backend],due to error: No module named 'backend.api_admin'
[2021-08-09 17:03:58] [ERROR] Fail to import application: [public],due to error: No module named 'public.api_admin'
[2021-08-09 17:03:59] [ERROR] Fail to import application: [django.contrib.admin],due to error: No module named 'django.contrib.admin.public_admin'
[2021-08-09 17:03:59] [ERROR] Fail to import application: [django.contrib.auth],due to error: No module named 'django.contrib.auth.public_admin'
[2021-08-09 17:03:59] [ERROR] Fail to import application: [django.contrib.contenttypes],due to error: No module named 'django.contrib.contenttypes.public_admin'
[2021-08-09 17:03:59] [ERROR] Fail to import application: [django.contrib.sessions],due to error: No module named 'django.contrib.sessions.public_admin'
[2021-08-09 17:03:59] [ERROR] Fail to import application: [django.contrib.messages],due to error: No module named 'django.contrib.messages.public_admin'
[2021-08-09 17:03:59] [ERROR] Fail to import application: [django.contrib.staticfiles],due to error: No module named 'django.contrib.staticfiles.public_admin'
[2021-08-09 17:03:59] [ERROR] Fail to import application: [api],due to error: No module named 'api.public_admin'
[2021-08-09 17:03:59] [ERROR] Fail to import application: [backend],due to error: No module named 'backend.public_admin'
[2021-08-09 17:03:59] [DEBUG] The application and model name are [('public', 'userprofile')]
[2021-08-09 17:03:59] [DEBUG] The application and model name are [('public', 'groups')]
[2021-08-09 17:03:59] [DEBUG] The application and model name are [('public', 'role')]
[2021-08-09 17:03:59] [DEBUG] The application and model name are [('public', 'firstlayermenu')]
[2021-08-09 17:03:59] [DEBUG] The application and model name are [('public', 'submenu')]
[2021-08-09 17:03:59] [DEBUG] The application and model name are [('public', 'businessfunc')]
[2021-08-09 17:03:59] [DEBUG] The application and model name are [('public', 'retrieval')]
[2021-08-09 17:03:59] [DEBUG] The application and model name are [('public', 'resource')]
[2021-08-09 17:03:59] [DEBUG] The application and model name are [('public', 'environment')]
[2021-08-09 17:03:59] [DEBUG] The application and model name are [('public', 'dbinfo')]
[2021-08-09 17:03:59] [DEBUG] The application and model name are [('public', 'logserverinfo')]
[2021-08-09 17:03:59] [DEBUG] The application and model name are [('public', 'configurations')]
[2021-08-09 17:03:59] [DEBUG] The application and model name are [('public', 'cn_en_map')]
[2021-08-09 17:03:59] [DEBUG] The application and model name are [('public', 'steplog')]
[2021-08-09 17:03:59] [DEBUG] The application and model name are [('public', 'todolist')]
[2021-08-09 17:03:59] [DEBUG] Success to import application :[public]
[2021-08-09 17:03:59] [ERROR] Fail to import application: [django.contrib.admin],due to error: No module named 'django.contrib.admin.api_admin'
[2021-08-09 17:03:59] [ERROR] Fail to import application: [django.contrib.auth],due to error: No module named 'django.contrib.auth.api_admin'
[2021-08-09 17:03:59] [ERROR] Fail to import application: [django.contrib.contenttypes],due to error: No module named 'django.contrib.contenttypes.api_admin'
[2021-08-09 17:03:59] [ERROR] Fail to import application: [django.contrib.sessions],due to error: No module named 'django.contrib.sessions.api_admin'
[2021-08-09 17:03:59] [ERROR] Fail to import application: [django.contrib.messages],due to error: No module named 'django.contrib.messages.api_admin'
[2021-08-09 17:03:59] [ERROR] Fail to import application: [django.contrib.staticfiles],due to error: No module named 'django.contrib.staticfiles.api_admin'
[2021-08-09 17:03:59] [DEBUG] Success to import application :[api]
[2021-08-09 17:03:59] [ERROR] Fail to import application: [backend],due to error: No module named 'backend.api_admin'
[2021-08-09 17:03:59] [ERROR] Fail to import application: [public],due to error: No module named 'public.api_admin'
[2021-08-09 17:03:59] [ERROR] Fail to import application: [django.contrib.admin],due to error: No module named 'django.contrib.admin.web_admin'
[2021-08-09 17:03:59] [ERROR] Fail to import application: [django.contrib.auth],due to error: No module named 'django.contrib.auth.web_admin'
[2021-08-09 17:03:59] [ERROR] Fail to import application: [django.contrib.contenttypes],due to error: No module named 'django.contrib.contenttypes.web_admin'
[2021-08-09 17:03:59] [ERROR] Fail to import application: [django.contrib.sessions],due to error: No module named 'django.contrib.sessions.web_admin'
[2021-08-09 17:03:59] [ERROR] Fail to import application: [django.contrib.messages],due to error: No module named 'django.contrib.messages.web_admin'
[2021-08-09 17:03:59] [ERROR] Fail to import application: [django.contrib.staticfiles],due to error: No module named 'django.contrib.staticfiles.web_admin'
[2021-08-09 17:03:59] [ERROR] Fail to import application: [api],due to error: No module named 'api.web_admin'
[2021-08-09 17:03:59] [ERROR] Fail to import application: [backend],due to error: No module named 'backend.web_admin'
[2021-08-09 17:03:59] [ERROR] Fail to import application: [public],due to error: No module named 'public.web_admin'
[2021-08-09 17:03:59] [DEBUG] 修剪后的全部项目信息:[{'上海证券交易所': [{'testsuit__module': 'KMS', 'testsuit__class_title': 'KMS系统', 'testsuit__testcase__case': 'login_kms', 'testsuit__testcase__case_title': 'KMS用户登录接口', 'testsuit__testcase__case_description': 'KMS用户登录接口', 'testsuit__testcase__templates__name': 'kms登录模板', 'testsuit__testcase__templates__url': 'http://119.123.2.1:8980/login', 'testsuit__testcase__templates__method': 1, 'testsuit__testcase__templates__header': "{'Content-Type':'application/json'}", 'testsuit__testcase__templates__data': '{\r\n     "id":"ewr3-deee3-2ewq2-uhue7",\r\n     "params":{\r\n            "name":"{{username}}",\r\n            "passcode":"{{password}}",\r\n            " check":"${check|<{{remember_flag}}>}"\r\n      }\r\n}', 'testsuit__testcase__scenario__scenario': '用户正确密码错误', 'testsuit__testcase__scenario__parameter': "[{'password': ' sdad@1332'}, {'username': 'zhangwenke'}, {'remember_flag': 'true'}]", 'testsuit__testcase__scenario__validator': "[{'code': 200}]"}, {'testsuit__module': 'KMS', 'testsuit__class_title': 'KMS系统', 'testsuit__testcase__case': 'login_kms', 'testsuit__testcase__case_title': 'KMS用户登录接口', 'testsuit__testcase__case_description': 'KMS用户登录接口', 'testsuit__testcase__templates__name': 'kms登录模板', 'testsuit__testcase__templates__url': 'http://119.123.2.1:8980/login', 'testsuit__testcase__templates__method': 1, 'testsuit__testcase__templates__header': "{'Content-Type':'application/json'}", 'testsuit__testcase__templates__data': '{\r\n     "id":"ewr3-deee3-2ewq2-uhue7",\r\n     "params":{\r\n            "name":"{{username}}",\r\n            "passcode":"{{password}}",\r\n            " check":"${check|<{{remember_flag}}>}"\r\n      }\r\n}', 'testsuit__testcase__scenario__scenario': '用户密码均正确', 'testsuit__testcase__scenario__parameter': "[{'password': 'aaaa1111!'}, {'username': 'zhangwenke'}, {'remember_flag': 'true'}]", 'testsuit__testcase__scenario__validator': "[{'code': 200}]"}]}, {'中国外汇交易中心项目': [{'testsuit__module': 'ODM', 'testsuit__class_title': 'ODM交易系统', 'testsuit__testcase__case': 'order_submit', 'testsuit__testcase__case_title': '限价订单提交', 'testsuit__testcase__case_description': None, 'testsuit__testcase__templates__name': '现券XBOND订单提交', 'testsuit__testcase__templates__url': 'https://www.cnblogs.com/aaronthon/ajax/GetPostStat', 'testsuit__testcase__templates__method': 1, 'testsuit__testcase__templates__header': '{"content-type": "application/json", "Authorization":"9480295ab2e2eddb8"}', 'testsuit__testcase__templates__data': '{\r\n    "ordrData": {\r\n      "clntQtCd": "",\r\n      "stlmntSpdNm": 2,\r\n      "cntngncyIndctr": null,\r\n      "flxblNetPrc": null,\r\n      "qtTp": "${login}|<{{username}},{{password}}>",\r\n      "netPrc": "{{netPrc}}",\r\n      "instnCd": "{{instnCd}}",\r\n      "nmnlVol": "{{volumn}}",\r\n      "ordrTpIndctr": "1"\r\n  }\r\n}', 'testsuit__testcase__scenario__scenario': '限价订单提交-T+1', 'testsuit__testcase__scenario__parameter': "[{'netPrc': '100.2344'}, {'password': 'aaaa1111!'}, {'instnCd': '100035'}, {'volumn': '1000,000'}, {'username': 'zhangwneke'}]", 'testsuit__testcase__scenario__validator': "[{'code': 200}, {'result': ' sussess'}]"}]}]
[2021-08-09 17:03:59] [DEBUG] 汇总后的全部项目信息为：[{'上海证券交易所': [{'KMS': [{'case': 'login_kms', 'case_title': 'KMS用户登录接口', 'case_description': 'KMS用户登录接口', 'templates__name': 'kms登录模板', 'url': 'http://119.123.2.1:8980/login', 'method': 1, 'header': {'Content-Type': 'application/json'}, 'data': {'id': 'ewr3-deee3-2ewq2-uhue7', 'params': {'name': '{{username}}', 'passcode': '{{password}}', ' check': '${check|<{{remember_flag}}>}'}}, 'scenarios': [{'parameter': [{'password': ' sdad@1332'}, {'username': 'zhangwenke'}, {'remember_flag': 'true'}], 'name': '用户正确密码错误', 'validator': [{'code': 200}]}, {'parameter': [{'password': 'aaaa1111!'}, {'username': 'zhangwenke'}, {'remember_flag': 'true'}], 'name': '用户密码均正确', 'validator': [{'code': 200}]}]}]}]}, {'中国外汇交易中心项目': [{'ODM': [{'case': 'order_submit', 'case_title': '限价订单提交', 'case_description': None, 'templates__name': '现券XBOND订单提交', 'url': 'https://www.cnblogs.com/aaronthon/ajax/GetPostStat', 'method': 1, 'header': {'content-type': 'application/json', 'Authorization': '9480295ab2e2eddb8'}, 'data': {'ordrData': {'clntQtCd': '', 'stlmntSpdNm': 2, 'cntngncyIndctr': '', 'flxblNetPrc': '', 'qtTp': '${login}|<{{username}},{{password}}>', 'netPrc': '{{netPrc}}', 'instnCd': '{{instnCd}}', 'nmnlVol': '{{volumn}}', 'ordrTpIndctr': '1'}}, 'scenarios': [{'parameter': [{'netPrc': '100.2344'}, {'password': 'aaaa1111!'}, {'instnCd': '100035'}, {'volumn': '1000,000'}, {'username': 'zhangwneke'}], 'name': '限价订单提交-T+1', 'validator': [{'code': 200}, {'result': ' sussess'}]}]}]}]}]
[2021-08-09 17:07:45] [DEBUG] Start to match permission: <class 'tuple'>
[2021-08-09 17:07:45] [DEBUG] The logined user is:{request.user,} and the current url is: {current_url_name}
[2021-08-09 17:07:45] [DEBUG] The permission list is: {permission_list}
[2021-08-09 17:07:45] [DEBUG] The permission group is: <QuerySet [('web_table_data',), ('web_table_update_view',), ('web_table_update',), ('web_table_add',), ('web_table_add_view',), ('web_table_delete_view',), ('password_reset_get',)]>
[2021-08-09 17:07:45] [DEBUG] The matched result is: [True, True, True]
[2021-08-09 17:07:45] [DEBUG] The permission name is: web_table_data and permissions are:[True, True, True]
[2021-08-09 17:07:45] [INFO] Splite the permission: f('web', 'table', 'data')
[2021-08-09 17:07:45] [DEBUG] Create permission: {perm_obj}
[2021-08-09 17:07:45] [INFO] The user have the permission!
[2021-08-09 17:07:45] [DEBUG] Prepare to execute: delete_selected!
[2021-08-09 17:07:45] [DEBUG] Prepare to execute: valid_selected!
[2021-08-09 17:07:45] [DEBUG] Prepare to execute: invalid_selected!
[2021-08-09 17:07:45] [DEBUG] Prepare to execute: model_actions!
[2021-08-09 17:07:45] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:07:45] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:07:45] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:07:45] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:07:45] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:07:45] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:07:45] [DEBUG] The user have access: <HttpResponse status_code=200, "text/html; charset=utf-8"> to get the page!
[2021-08-09 17:07:45] [DEBUG] Prepare to execute: delete_selected!
[2021-08-09 17:07:45] [DEBUG] Prepare to execute: valid_selected!
[2021-08-09 17:07:45] [DEBUG] Prepare to execute: invalid_selected!
[2021-08-09 17:07:45] [DEBUG] Prepare to execute: model_actions!
[2021-08-09 17:07:45] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:07:45] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:07:45] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:07:45] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:07:45] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:07:45] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:08:11] [DEBUG] 修剪后的全部项目信息:[{'上海证券交易所': [{'testsuit__module': 'KMS', 'testsuit__class_title': 'KMS系统', 'testsuit__testcase__case': 'login_kms', 'testsuit__testcase__case_title': 'KMS用户登录接口', 'testsuit__testcase__case_description': 'KMS用户登录接口', 'testsuit__testcase__templates__name': 'kms登录模板', 'testsuit__testcase__templates__url': 'http://119.123.2.1:8980/login', 'testsuit__testcase__templates__method': 1, 'testsuit__testcase__templates__header': "{'Content-Type':'application/json'}", 'testsuit__testcase__templates__data': '{\r\n     "id":"ewr3-deee3-2ewq2-uhue7",\r\n     "params":{\r\n            "name":"{{username}}",\r\n            "passcode":"{{password}}",\r\n            " check":"${check|<{{remember_flag}}>}"\r\n      }\r\n}', 'testsuit__testcase__scenario__scenario': '用户正确密码错误', 'testsuit__testcase__scenario__parameter': "[{'password': ' sdad@1332'}, {'username': 'zhangwenke'}, {'remember_flag': 'true'}]", 'testsuit__testcase__scenario__validator': "[{'code': 200}]"}, {'testsuit__module': 'KMS', 'testsuit__class_title': 'KMS系统', 'testsuit__testcase__case': 'login_kms', 'testsuit__testcase__case_title': 'KMS用户登录接口', 'testsuit__testcase__case_description': 'KMS用户登录接口', 'testsuit__testcase__templates__name': 'kms登录模板', 'testsuit__testcase__templates__url': 'http://119.123.2.1:8980/login', 'testsuit__testcase__templates__method': 1, 'testsuit__testcase__templates__header': "{'Content-Type':'application/json'}", 'testsuit__testcase__templates__data': '{\r\n     "id":"ewr3-deee3-2ewq2-uhue7",\r\n     "params":{\r\n            "name":"{{username}}",\r\n            "passcode":"{{password}}",\r\n            " check":"${check|<{{remember_flag}}>}"\r\n      }\r\n}', 'testsuit__testcase__scenario__scenario': '用户密码均正确', 'testsuit__testcase__scenario__parameter': "[{'password': 'aaaa1111!'}, {'username': 'zhangwenke'}, {'remember_flag': 'true'}]", 'testsuit__testcase__scenario__validator': "[{'code': 200}]"}]}, {'中国外汇交易中心项目': [{'testsuit__module': 'ODM', 'testsuit__class_title': 'ODM交易系统', 'testsuit__testcase__case': 'order_submit', 'testsuit__testcase__case_title': '限价订单提交', 'testsuit__testcase__case_description': None, 'testsuit__testcase__templates__name': '现券XBOND订单提交', 'testsuit__testcase__templates__url': 'https://www.cnblogs.com/aaronthon/ajax/GetPostStat', 'testsuit__testcase__templates__method': 1, 'testsuit__testcase__templates__header': '{"content-type": "application/json", "Authorization":"9480295ab2e2eddb8"}', 'testsuit__testcase__templates__data': '{\r\n    "ordrData": {\r\n      "clntQtCd": "",\r\n      "stlmntSpdNm": 2,\r\n      "cntngncyIndctr": null,\r\n      "flxblNetPrc": null,\r\n      "qtTp": "${login}|<{{username}},{{password}}>",\r\n      "netPrc": "{{netPrc}}",\r\n      "instnCd": "{{instnCd}}",\r\n      "nmnlVol": "{{volumn}}",\r\n      "ordrTpIndctr": "1"\r\n  }\r\n}', 'testsuit__testcase__scenario__scenario': '限价订单提交-T+1', 'testsuit__testcase__scenario__parameter': "[{'netPrc': '100.2344'}, {'password': 'aaaa1111!'}, {'instnCd': '100035'}, {'volumn': '1000,000'}, {'username': 'zhangwneke'}]", 'testsuit__testcase__scenario__validator': "[{'code': 200}, {'result': ' sussess'}]"}]}]
[2021-08-09 17:08:11] [DEBUG] 汇总后的全部项目信息为：[{'上海证券交易所': [{'KMS': [{'case': 'login_kms', 'case_title': 'KMS用户登录接口', 'case_description': 'KMS用户登录接口', 'templates__name': 'kms登录模板', 'url': 'http://119.123.2.1:8980/login', 'method': 1, 'header': {'Content-Type': 'application/json'}, 'data': {'id': 'ewr3-deee3-2ewq2-uhue7', 'params': {'name': '{{username}}', 'passcode': '{{password}}', ' check': '${check|<{{remember_flag}}>}'}}, 'scenarios': [{'parameter': [{'password': ' sdad@1332'}, {'username': 'zhangwenke'}, {'remember_flag': 'true'}], 'name': '用户正确密码错误', 'validator': [{'code': 200}]}, {'parameter': [{'password': 'aaaa1111!'}, {'username': 'zhangwenke'}, {'remember_flag': 'true'}], 'name': '用户密码均正确', 'validator': [{'code': 200}]}]}]}]}, {'中国外汇交易中心项目': [{'ODM': [{'case': 'order_submit', 'case_title': '限价订单提交', 'case_description': None, 'templates__name': '现券XBOND订单提交', 'url': 'https://www.cnblogs.com/aaronthon/ajax/GetPostStat', 'method': 1, 'header': {'content-type': 'application/json', 'Authorization': '9480295ab2e2eddb8'}, 'data': {'ordrData': {'clntQtCd': '', 'stlmntSpdNm': 2, 'cntngncyIndctr': '', 'flxblNetPrc': '', 'qtTp': '${login}|<{{username}},{{password}}>', 'netPrc': '{{netPrc}}', 'instnCd': '{{instnCd}}', 'nmnlVol': '{{volumn}}', 'ordrTpIndctr': '1'}}, 'scenarios': [{'parameter': [{'netPrc': '100.2344'}, {'password': 'aaaa1111!'}, {'instnCd': '100035'}, {'volumn': '1000,000'}, {'username': 'zhangwneke'}], 'name': '限价订单提交-T+1', 'validator': [{'code': 200}, {'result': ' sussess'}]}]}]}]}]
[2021-08-09 17:08:15] [DEBUG] Start to match permission: <class 'tuple'>
[2021-08-09 17:08:15] [DEBUG] The logined user is:{request.user,} and the current url is: {current_url_name}
[2021-08-09 17:08:15] [DEBUG] The permission list is: {permission_list}
[2021-08-09 17:08:15] [DEBUG] The permission group is: <QuerySet [('web_table_data',), ('web_table_update_view',), ('web_table_update',), ('web_table_add',), ('web_table_add_view',), ('web_table_delete_view',), ('password_reset_get',)]>
[2021-08-09 17:08:15] [DEBUG] The matched result is: [True, True, True]
[2021-08-09 17:08:15] [DEBUG] The permission name is: web_table_data and permissions are:[True, True, True]
[2021-08-09 17:08:15] [INFO] Splite the permission: f('web', 'table', 'data')
[2021-08-09 17:08:15] [DEBUG] Create permission: {perm_obj}
[2021-08-09 17:08:15] [INFO] The user have the permission!
[2021-08-09 17:08:15] [DEBUG] Prepare to execute: delete_selected!
[2021-08-09 17:08:15] [DEBUG] Prepare to execute: valid_selected!
[2021-08-09 17:08:15] [DEBUG] Prepare to execute: invalid_selected!
[2021-08-09 17:08:15] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:08:15] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:08:15] [DEBUG] The user have access: <HttpResponse status_code=200, "text/html; charset=utf-8"> to get the page!
[2021-08-09 17:08:15] [DEBUG] Prepare to execute: delete_selected!
[2021-08-09 17:08:15] [DEBUG] Prepare to execute: valid_selected!
[2021-08-09 17:08:15] [DEBUG] Prepare to execute: invalid_selected!
[2021-08-09 17:08:15] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:08:15] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:08:28] [DEBUG] 修剪后的全部项目信息:[{'上海证券交易所': [{'testsuit__module': 'KMS', 'testsuit__class_title': 'KMS系统', 'testsuit__testcase__case': 'login_kms', 'testsuit__testcase__case_title': 'KMS用户登录接口', 'testsuit__testcase__case_description': 'KMS用户登录接口', 'testsuit__testcase__templates__name': 'kms登录模板', 'testsuit__testcase__templates__url': 'http://119.123.2.1:8980/login', 'testsuit__testcase__templates__method': 1, 'testsuit__testcase__templates__header': "{'Content-Type':'application/json'}", 'testsuit__testcase__templates__data': '{\r\n     "id":"ewr3-deee3-2ewq2-uhue7",\r\n     "params":{\r\n            "name":"{{username}}",\r\n            "passcode":"{{password}}",\r\n            " check":"${check|<{{remember_flag}}>}"\r\n      }\r\n}', 'testsuit__testcase__scenario__scenario': '用户正确密码错误', 'testsuit__testcase__scenario__parameter': "[{'password': ' sdad@1332'}, {'username': 'zhangwenke'}, {'remember_flag': 'true'}]", 'testsuit__testcase__scenario__validator': "[{'code': 200}]"}, {'testsuit__module': 'KMS', 'testsuit__class_title': 'KMS系统', 'testsuit__testcase__case': 'login_kms', 'testsuit__testcase__case_title': 'KMS用户登录接口', 'testsuit__testcase__case_description': 'KMS用户登录接口', 'testsuit__testcase__templates__name': 'kms登录模板', 'testsuit__testcase__templates__url': 'http://119.123.2.1:8980/login', 'testsuit__testcase__templates__method': 1, 'testsuit__testcase__templates__header': "{'Content-Type':'application/json'}", 'testsuit__testcase__templates__data': '{\r\n     "id":"ewr3-deee3-2ewq2-uhue7",\r\n     "params":{\r\n            "name":"{{username}}",\r\n            "passcode":"{{password}}",\r\n            " check":"${check|<{{remember_flag}}>}"\r\n      }\r\n}', 'testsuit__testcase__scenario__scenario': '用户密码均正确', 'testsuit__testcase__scenario__parameter': "[{'password': 'aaaa1111!'}, {'username': 'zhangwenke'}, {'remember_flag': 'true'}]", 'testsuit__testcase__scenario__validator': "[{'code': 200}]"}]}, {'中国外汇交易中心项目': [{'testsuit__module': 'ODM', 'testsuit__class_title': 'ODM交易系统', 'testsuit__testcase__case': 'order_submit', 'testsuit__testcase__case_title': '限价订单提交', 'testsuit__testcase__case_description': None, 'testsuit__testcase__templates__name': '现券XBOND订单提交', 'testsuit__testcase__templates__url': 'https://www.cnblogs.com/aaronthon/ajax/GetPostStat', 'testsuit__testcase__templates__method': 1, 'testsuit__testcase__templates__header': '{"content-type": "application/json", "Authorization":"9480295ab2e2eddb8"}', 'testsuit__testcase__templates__data': '{\r\n    "ordrData": {\r\n      "clntQtCd": "",\r\n      "stlmntSpdNm": 2,\r\n      "cntngncyIndctr": null,\r\n      "flxblNetPrc": null,\r\n      "qtTp": "${login}|<{{username}},{{password}}>",\r\n      "netPrc": "{{netPrc}}",\r\n      "instnCd": "{{instnCd}}",\r\n      "nmnlVol": "{{volumn}}",\r\n      "ordrTpIndctr": "1"\r\n  }\r\n}', 'testsuit__testcase__scenario__scenario': '限价订单提交-T+1', 'testsuit__testcase__scenario__parameter': "[{'netPrc': '100.2344'}, {'password': 'aaaa1111!'}, {'instnCd': '100035'}, {'volumn': '1000,000'}, {'username': 'zhangwneke'}]", 'testsuit__testcase__scenario__validator': "[{'code': 200}, {'result': ' sussess'}]"}]}]
[2021-08-09 17:08:28] [DEBUG] 汇总后的全部项目信息为：[{'上海证券交易所': [{'KMS': [{'case': 'login_kms', 'case_title': 'KMS用户登录接口', 'case_description': 'KMS用户登录接口', 'templates__name': 'kms登录模板', 'url': 'http://119.123.2.1:8980/login', 'method': 1, 'header': {'Content-Type': 'application/json'}, 'data': {'id': 'ewr3-deee3-2ewq2-uhue7', 'params': {'name': '{{username}}', 'passcode': '{{password}}', ' check': '${check|<{{remember_flag}}>}'}}, 'scenarios': [{'parameter': [{'password': ' sdad@1332'}, {'username': 'zhangwenke'}, {'remember_flag': 'true'}], 'name': '用户正确密码错误', 'validator': [{'code': 200}]}, {'parameter': [{'password': 'aaaa1111!'}, {'username': 'zhangwenke'}, {'remember_flag': 'true'}], 'name': '用户密码均正确', 'validator': [{'code': 200}]}]}]}]}, {'中国外汇交易中心项目': [{'ODM': [{'case': 'order_submit', 'case_title': '限价订单提交', 'case_description': None, 'templates__name': '现券XBOND订单提交', 'url': 'https://www.cnblogs.com/aaronthon/ajax/GetPostStat', 'method': 1, 'header': {'content-type': 'application/json', 'Authorization': '9480295ab2e2eddb8'}, 'data': {'ordrData': {'clntQtCd': '', 'stlmntSpdNm': 2, 'cntngncyIndctr': '', 'flxblNetPrc': '', 'qtTp': '${login}|<{{username}},{{password}}>', 'netPrc': '{{netPrc}}', 'instnCd': '{{instnCd}}', 'nmnlVol': '{{volumn}}', 'ordrTpIndctr': '1'}}, 'scenarios': [{'parameter': [{'netPrc': '100.2344'}, {'password': 'aaaa1111!'}, {'instnCd': '100035'}, {'volumn': '1000,000'}, {'username': 'zhangwneke'}], 'name': '限价订单提交-T+1', 'validator': [{'code': 200}, {'result': ' sussess'}]}]}]}]}]
[2021-08-09 17:08:31] [DEBUG] Start to match permission: <class 'tuple'>
[2021-08-09 17:08:31] [DEBUG] The logined user is:{request.user,} and the current url is: {current_url_name}
[2021-08-09 17:08:31] [DEBUG] The permission list is: {permission_list}
[2021-08-09 17:08:31] [DEBUG] The permission group is: <QuerySet [('web_table_data',), ('web_table_update_view',), ('web_table_update',), ('web_table_add',), ('web_table_add_view',), ('web_table_delete_view',), ('password_reset_get',)]>
[2021-08-09 17:08:31] [DEBUG] The matched result is: [True, True, True]
[2021-08-09 17:08:31] [DEBUG] The permission name is: web_table_data and permissions are:[True, True, True]
[2021-08-09 17:08:31] [INFO] Splite the permission: f('web', 'table', 'data')
[2021-08-09 17:08:31] [DEBUG] Create permission: {perm_obj}
[2021-08-09 17:08:31] [INFO] The user have the permission!
[2021-08-09 17:08:32] [DEBUG] Prepare to execute: delete_selected!
[2021-08-09 17:08:32] [DEBUG] Prepare to execute: valid_selected!
[2021-08-09 17:08:32] [DEBUG] Prepare to execute: invalid_selected!
[2021-08-09 17:08:32] [DEBUG] Prepare to execute: model_actions!
[2021-08-09 17:08:32] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:08:32] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:08:32] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:08:32] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:08:32] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:08:32] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:08:32] [DEBUG] The user have access: <HttpResponse status_code=200, "text/html; charset=utf-8"> to get the page!
[2021-08-09 17:08:32] [DEBUG] Prepare to execute: delete_selected!
[2021-08-09 17:08:32] [DEBUG] Prepare to execute: valid_selected!
[2021-08-09 17:08:32] [DEBUG] Prepare to execute: invalid_selected!
[2021-08-09 17:08:32] [DEBUG] Prepare to execute: model_actions!
[2021-08-09 17:08:32] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:08:32] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:08:32] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:08:32] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:08:32] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:08:32] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:08:41] [DEBUG] Start to match permission: <class 'tuple'>
[2021-08-09 17:08:41] [DEBUG] The logined user is:{request.user,} and the current url is: {current_url_name}
[2021-08-09 17:08:41] [DEBUG] The permission list is: {permission_list}
[2021-08-09 17:08:41] [DEBUG] The permission group is: <QuerySet [('web_table_data',), ('web_table_update_view',), ('web_table_update',), ('web_table_add',), ('web_table_add_view',), ('web_table_delete_view',), ('password_reset_get',)]>
[2021-08-09 17:08:41] [DEBUG] The matched result is: [True, True, True]
[2021-08-09 17:08:41] [DEBUG] The permission name is: web_table_update_view and permissions are:[True, True, True]
[2021-08-09 17:08:41] [INFO] Splite the permission: f('web', 'table', 'update', 'view')
[2021-08-09 17:08:41] [DEBUG] Create permission: {perm_obj}
[2021-08-09 17:08:41] [INFO] The user have the permission!
[2021-08-09 17:08:41] [DEBUG] The user have access: <HttpResponse status_code=200, "text/html; charset=utf-8"> to get the page!
[2021-08-09 17:08:49] [DEBUG] Start to match permission: <class 'tuple'>
[2021-08-09 17:08:49] [DEBUG] The logined user is:{request.user,} and the current url is: {current_url_name}
[2021-08-09 17:08:49] [DEBUG] The permission list is: {permission_list}
[2021-08-09 17:08:49] [DEBUG] The permission group is: <QuerySet [('web_table_data',), ('web_table_update_view',), ('web_table_update',), ('web_table_add',), ('web_table_add_view',), ('web_table_delete_view',), ('password_reset_get',)]>
[2021-08-09 17:08:49] [DEBUG] The matched result is: [True, True, True]
[2021-08-09 17:08:49] [DEBUG] The permission name is: web_table_data and permissions are:[True, True, True]
[2021-08-09 17:08:49] [INFO] Splite the permission: f('web', 'table', 'data')
[2021-08-09 17:08:49] [DEBUG] Create permission: {perm_obj}
[2021-08-09 17:08:49] [INFO] The user have the permission!
[2021-08-09 17:08:49] [DEBUG] Prepare to execute: delete_selected!
[2021-08-09 17:08:49] [DEBUG] Prepare to execute: valid_selected!
[2021-08-09 17:08:49] [DEBUG] Prepare to execute: invalid_selected!
[2021-08-09 17:08:49] [DEBUG] Prepare to execute: model_actions!
[2021-08-09 17:08:49] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:08:49] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:08:49] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:08:49] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:08:49] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:08:49] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:08:49] [DEBUG] The user have access: <HttpResponse status_code=200, "text/html; charset=utf-8"> to get the page!
[2021-08-09 17:08:49] [DEBUG] Prepare to execute: delete_selected!
[2021-08-09 17:08:49] [DEBUG] Prepare to execute: valid_selected!
[2021-08-09 17:08:49] [DEBUG] Prepare to execute: invalid_selected!
[2021-08-09 17:08:49] [DEBUG] Prepare to execute: model_actions!
[2021-08-09 17:08:49] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:08:49] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:08:49] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:08:49] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:08:49] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:08:49] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:08:53] [DEBUG] Start to match permission: <class 'tuple'>
[2021-08-09 17:08:53] [DEBUG] The logined user is:{request.user,} and the current url is: {current_url_name}
[2021-08-09 17:08:53] [DEBUG] The permission list is: {permission_list}
[2021-08-09 17:08:53] [DEBUG] The permission group is: <QuerySet [('web_table_data',), ('web_table_update_view',), ('web_table_update',), ('web_table_add',), ('web_table_add_view',), ('web_table_delete_view',), ('password_reset_get',)]>
[2021-08-09 17:08:53] [DEBUG] The matched result is: [True, True, True]
[2021-08-09 17:08:53] [DEBUG] The permission name is: web_table_update_view and permissions are:[True, True, True]
[2021-08-09 17:08:53] [INFO] Splite the permission: f('web', 'table', 'update', 'view')
[2021-08-09 17:08:53] [DEBUG] Create permission: {perm_obj}
[2021-08-09 17:08:53] [INFO] The user have the permission!
[2021-08-09 17:08:53] [DEBUG] The user have access: <HttpResponse status_code=200, "text/html; charset=utf-8"> to get the page!
[2021-08-09 17:08:56] [DEBUG] Start to match permission: <class 'tuple'>
[2021-08-09 17:08:56] [DEBUG] The logined user is:{request.user,} and the current url is: {current_url_name}
[2021-08-09 17:08:56] [DEBUG] The permission list is: {permission_list}
[2021-08-09 17:08:56] [DEBUG] The permission group is: <QuerySet [('web_table_data',), ('web_table_update_view',), ('web_table_update',), ('web_table_add',), ('web_table_add_view',), ('web_table_delete_view',), ('password_reset_get',)]>
[2021-08-09 17:08:56] [DEBUG] The matched result is: [True, True, True]
[2021-08-09 17:08:56] [DEBUG] The permission name is: web_table_data and permissions are:[True, True, True]
[2021-08-09 17:08:56] [INFO] Splite the permission: f('web', 'table', 'data')
[2021-08-09 17:08:56] [DEBUG] Create permission: {perm_obj}
[2021-08-09 17:08:56] [INFO] The user have the permission!
[2021-08-09 17:08:56] [DEBUG] Prepare to execute: delete_selected!
[2021-08-09 17:08:56] [DEBUG] Prepare to execute: valid_selected!
[2021-08-09 17:08:56] [DEBUG] Prepare to execute: invalid_selected!
[2021-08-09 17:08:56] [DEBUG] Prepare to execute: model_actions!
[2021-08-09 17:08:56] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:08:56] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:08:56] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:08:56] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:08:56] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:08:56] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:08:56] [DEBUG] The user have access: <HttpResponse status_code=200, "text/html; charset=utf-8"> to get the page!
[2021-08-09 17:08:56] [DEBUG] Prepare to execute: delete_selected!
[2021-08-09 17:08:56] [DEBUG] Prepare to execute: valid_selected!
[2021-08-09 17:08:56] [DEBUG] Prepare to execute: invalid_selected!
[2021-08-09 17:08:56] [DEBUG] Prepare to execute: model_actions!
[2021-08-09 17:08:56] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:08:56] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:08:56] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:08:56] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:08:56] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:08:56] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:08:57] [DEBUG] Start to match permission: <class 'tuple'>
[2021-08-09 17:08:57] [DEBUG] The logined user is:{request.user,} and the current url is: {current_url_name}
[2021-08-09 17:08:57] [DEBUG] The permission list is: {permission_list}
[2021-08-09 17:08:57] [DEBUG] The permission group is: <QuerySet [('web_table_data',), ('web_table_update_view',), ('web_table_update',), ('web_table_add',), ('web_table_add_view',), ('web_table_delete_view',), ('password_reset_get',)]>
[2021-08-09 17:08:57] [DEBUG] The matched result is: [True, True, True]
[2021-08-09 17:08:57] [DEBUG] The permission name is: web_table_update_view and permissions are:[True, True, True]
[2021-08-09 17:08:57] [INFO] Splite the permission: f('web', 'table', 'update', 'view')
[2021-08-09 17:08:57] [DEBUG] Create permission: {perm_obj}
[2021-08-09 17:08:57] [INFO] The user have the permission!
[2021-08-09 17:08:58] [DEBUG] The user have access: <HttpResponse status_code=200, "text/html; charset=utf-8"> to get the page!
[2021-08-09 17:09:00] [DEBUG] Start to match permission: <class 'tuple'>
[2021-08-09 17:09:00] [DEBUG] The logined user is:{request.user,} and the current url is: {current_url_name}
[2021-08-09 17:09:00] [DEBUG] The permission list is: {permission_list}
[2021-08-09 17:09:00] [DEBUG] The permission group is: <QuerySet [('web_table_data',), ('web_table_update_view',), ('web_table_update',), ('web_table_add',), ('web_table_add_view',), ('web_table_delete_view',), ('password_reset_get',)]>
[2021-08-09 17:09:00] [DEBUG] The matched result is: [True, True, True]
[2021-08-09 17:09:00] [DEBUG] The permission name is: web_table_update and permissions are:[True, True, True]
[2021-08-09 17:09:00] [INFO] Splite the permission: f('web', 'table', 'update')
[2021-08-09 17:09:00] [DEBUG] Create permission: {perm_obj}
[2021-08-09 17:09:00] [INFO] The user have the permission!
[2021-08-09 17:09:02] [DEBUG] The user have access: <HttpResponseRedirect status_code=302, "text/html; charset=utf-8", url="/api/testsuit/"> to get the page!
[2021-08-09 17:09:03] [DEBUG] Start to match permission: <class 'tuple'>
[2021-08-09 17:09:03] [DEBUG] The logined user is:{request.user,} and the current url is: {current_url_name}
[2021-08-09 17:09:03] [DEBUG] The permission list is: {permission_list}
[2021-08-09 17:09:03] [DEBUG] The permission group is: <QuerySet [('web_table_data',), ('web_table_update_view',), ('web_table_update',), ('web_table_add',), ('web_table_add_view',), ('web_table_delete_view',), ('password_reset_get',)]>
[2021-08-09 17:09:03] [DEBUG] The matched result is: [True, True, True]
[2021-08-09 17:09:03] [DEBUG] The permission name is: web_table_data and permissions are:[True, True, True]
[2021-08-09 17:09:03] [INFO] Splite the permission: f('web', 'table', 'data')
[2021-08-09 17:09:03] [DEBUG] Create permission: {perm_obj}
[2021-08-09 17:09:03] [INFO] The user have the permission!
[2021-08-09 17:09:03] [DEBUG] Prepare to execute: delete_selected!
[2021-08-09 17:09:03] [DEBUG] Prepare to execute: valid_selected!
[2021-08-09 17:09:03] [DEBUG] Prepare to execute: invalid_selected!
[2021-08-09 17:09:03] [DEBUG] Prepare to execute: model_actions!
[2021-08-09 17:09:03] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:09:03] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:09:03] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:09:03] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:09:03] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:09:03] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:09:03] [DEBUG] The user have access: <HttpResponse status_code=200, "text/html; charset=utf-8"> to get the page!
[2021-08-09 17:09:03] [DEBUG] Prepare to execute: delete_selected!
[2021-08-09 17:09:03] [DEBUG] Prepare to execute: valid_selected!
[2021-08-09 17:09:03] [DEBUG] Prepare to execute: invalid_selected!
[2021-08-09 17:09:03] [DEBUG] Prepare to execute: model_actions!
[2021-08-09 17:09:03] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:09:03] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:09:03] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:09:03] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:09:03] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:09:03] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:09:36] [DEBUG] 修剪后的全部项目信息:[{'上海证券交易所': [{'testsuit__module': 'KMS', 'testsuit__class_title': 'KMS系统', 'testsuit__testcase__case': 'login_kms', 'testsuit__testcase__case_title': 'KMS用户登录接口', 'testsuit__testcase__case_description': 'KMS用户登录接口', 'testsuit__testcase__templates__name': 'kms登录模板', 'testsuit__testcase__templates__url': 'http://119.123.2.1:8980/login', 'testsuit__testcase__templates__method': 1, 'testsuit__testcase__templates__header': "{'Content-Type':'application/json'}", 'testsuit__testcase__templates__data': '{\r\n     "id":"ewr3-deee3-2ewq2-uhue7",\r\n     "params":{\r\n            "name":"{{username}}",\r\n            "passcode":"{{password}}",\r\n            " check":"${check|<{{remember_flag}}>}"\r\n      }\r\n}', 'testsuit__testcase__scenario__scenario': '用户正确密码错误', 'testsuit__testcase__scenario__parameter': "[{'password': ' sdad@1332'}, {'username': 'zhangwenke'}, {'remember_flag': 'true'}]", 'testsuit__testcase__scenario__validator': "[{'code': 200}]"}, {'testsuit__module': 'KMS', 'testsuit__class_title': 'KMS系统', 'testsuit__testcase__case': 'login_kms', 'testsuit__testcase__case_title': 'KMS用户登录接口', 'testsuit__testcase__case_description': 'KMS用户登录接口', 'testsuit__testcase__templates__name': 'kms登录模板', 'testsuit__testcase__templates__url': 'http://119.123.2.1:8980/login', 'testsuit__testcase__templates__method': 1, 'testsuit__testcase__templates__header': "{'Content-Type':'application/json'}", 'testsuit__testcase__templates__data': '{\r\n     "id":"ewr3-deee3-2ewq2-uhue7",\r\n     "params":{\r\n            "name":"{{username}}",\r\n            "passcode":"{{password}}",\r\n            " check":"${check|<{{remember_flag}}>}"\r\n      }\r\n}', 'testsuit__testcase__scenario__scenario': '用户密码均正确', 'testsuit__testcase__scenario__parameter': "[{'password': 'aaaa1111!'}, {'username': 'zhangwenke'}, {'remember_flag': 'true'}]", 'testsuit__testcase__scenario__validator': "[{'code': 200}]"}]}, {'中国外汇交易中心项目': [{'testsuit__module': 'ODM', 'testsuit__class_title': 'ODM交易系统', 'testsuit__testcase__case': 'order_submit', 'testsuit__testcase__case_title': '限价订单提交', 'testsuit__testcase__case_description': None, 'testsuit__testcase__templates__name': '现券XBOND订单提交', 'testsuit__testcase__templates__url': 'https://www.cnblogs.com/aaronthon/ajax/GetPostStat', 'testsuit__testcase__templates__method': 1, 'testsuit__testcase__templates__header': '{"content-type": "application/json", "Authorization":"9480295ab2e2eddb8"}', 'testsuit__testcase__templates__data': '{\r\n    "ordrData": {\r\n      "clntQtCd": "",\r\n      "stlmntSpdNm": 2,\r\n      "cntngncyIndctr": null,\r\n      "flxblNetPrc": null,\r\n      "qtTp": "${login}|<{{username}},{{password}}>",\r\n      "netPrc": "{{netPrc}}",\r\n      "instnCd": "{{instnCd}}",\r\n      "nmnlVol": "{{volumn}}",\r\n      "ordrTpIndctr": "1"\r\n  }\r\n}', 'testsuit__testcase__scenario__scenario': '限价订单提交-T+1', 'testsuit__testcase__scenario__parameter': "[{'netPrc': '100.2344'}, {'password': 'aaaa1111!'}, {'instnCd': '100035'}, {'volumn': '1000,000'}, {'username': 'zhangwneke'}]", 'testsuit__testcase__scenario__validator': "[{'code': 200}, {'result': ' sussess'}]"}]}]
[2021-08-09 17:09:36] [DEBUG] 汇总后的全部项目信息为：[{'上海证券交易所': [{'KMS': [{'case': 'login_kms', 'case_title': 'KMS用户登录接口', 'case_description': 'KMS用户登录接口', 'templates__name': 'kms登录模板', 'url': 'http://119.123.2.1:8980/login', 'method': 1, 'header': {'Content-Type': 'application/json'}, 'data': {'id': 'ewr3-deee3-2ewq2-uhue7', 'params': {'name': '{{username}}', 'passcode': '{{password}}', ' check': '${check|<{{remember_flag}}>}'}}, 'scenarios': [{'parameter': [{'password': ' sdad@1332'}, {'username': 'zhangwenke'}, {'remember_flag': 'true'}], 'name': '用户正确密码错误', 'validator': [{'code': 200}]}, {'parameter': [{'password': 'aaaa1111!'}, {'username': 'zhangwenke'}, {'remember_flag': 'true'}], 'name': '用户密码均正确', 'validator': [{'code': 200}]}]}]}]}, {'中国外汇交易中心项目': [{'ODM': [{'case': 'order_submit', 'case_title': '限价订单提交', 'case_description': None, 'templates__name': '现券XBOND订单提交', 'url': 'https://www.cnblogs.com/aaronthon/ajax/GetPostStat', 'method': 1, 'header': {'content-type': 'application/json', 'Authorization': '9480295ab2e2eddb8'}, 'data': {'ordrData': {'clntQtCd': '', 'stlmntSpdNm': 2, 'cntngncyIndctr': '', 'flxblNetPrc': '', 'qtTp': '${login}|<{{username}},{{password}}>', 'netPrc': '{{netPrc}}', 'instnCd': '{{instnCd}}', 'nmnlVol': '{{volumn}}', 'ordrTpIndctr': '1'}}, 'scenarios': [{'parameter': [{'netPrc': '100.2344'}, {'password': 'aaaa1111!'}, {'instnCd': '100035'}, {'volumn': '1000,000'}, {'username': 'zhangwneke'}], 'name': '限价订单提交-T+1', 'validator': [{'code': 200}, {'result': ' sussess'}]}]}]}]}]
[2021-08-09 17:09:38] [DEBUG] Start to match permission: <class 'tuple'>
[2021-08-09 17:09:38] [DEBUG] The logined user is:{request.user,} and the current url is: {current_url_name}
[2021-08-09 17:09:38] [DEBUG] The permission list is: {permission_list}
[2021-08-09 17:09:38] [DEBUG] The permission group is: <QuerySet [('web_table_data',), ('web_table_update_view',), ('web_table_update',), ('web_table_add',), ('web_table_add_view',), ('web_table_delete_view',), ('password_reset_get',)]>
[2021-08-09 17:09:38] [DEBUG] The matched result is: [True, True, True]
[2021-08-09 17:09:38] [DEBUG] The permission name is: web_table_data and permissions are:[True, True, True]
[2021-08-09 17:09:38] [INFO] Splite the permission: f('web', 'table', 'data')
[2021-08-09 17:09:38] [DEBUG] Create permission: {perm_obj}
[2021-08-09 17:09:38] [INFO] The user have the permission!
[2021-08-09 17:09:38] [DEBUG] Prepare to execute: delete_selected!
[2021-08-09 17:09:38] [DEBUG] Prepare to execute: valid_selected!
[2021-08-09 17:09:38] [DEBUG] Prepare to execute: invalid_selected!
[2021-08-09 17:09:38] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:09:38] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:09:38] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:09:38] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:09:38] [DEBUG] The user have access: <HttpResponse status_code=200, "text/html; charset=utf-8"> to get the page!
[2021-08-09 17:09:39] [DEBUG] Prepare to execute: delete_selected!
[2021-08-09 17:09:39] [DEBUG] Prepare to execute: valid_selected!
[2021-08-09 17:09:39] [DEBUG] Prepare to execute: invalid_selected!
[2021-08-09 17:09:39] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:09:39] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:09:39] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:09:39] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:09:44] [DEBUG] 修剪后的全部项目信息:[{'上海证券交易所': [{'testsuit__module': 'KMS', 'testsuit__class_title': 'KMS系统', 'testsuit__testcase__case': 'login_kms', 'testsuit__testcase__case_title': 'KMS用户登录接口', 'testsuit__testcase__case_description': 'KMS用户登录接口', 'testsuit__testcase__templates__name': 'kms登录模板', 'testsuit__testcase__templates__url': 'http://119.123.2.1:8980/login', 'testsuit__testcase__templates__method': 1, 'testsuit__testcase__templates__header': "{'Content-Type':'application/json'}", 'testsuit__testcase__templates__data': '{\r\n     "id":"ewr3-deee3-2ewq2-uhue7",\r\n     "params":{\r\n            "name":"{{username}}",\r\n            "passcode":"{{password}}",\r\n            " check":"${check|<{{remember_flag}}>}"\r\n      }\r\n}', 'testsuit__testcase__scenario__scenario': '用户正确密码错误', 'testsuit__testcase__scenario__parameter': "[{'password': ' sdad@1332'}, {'username': 'zhangwenke'}, {'remember_flag': 'true'}]", 'testsuit__testcase__scenario__validator': "[{'code': 200}]"}, {'testsuit__module': 'KMS', 'testsuit__class_title': 'KMS系统', 'testsuit__testcase__case': 'login_kms', 'testsuit__testcase__case_title': 'KMS用户登录接口', 'testsuit__testcase__case_description': 'KMS用户登录接口', 'testsuit__testcase__templates__name': 'kms登录模板', 'testsuit__testcase__templates__url': 'http://119.123.2.1:8980/login', 'testsuit__testcase__templates__method': 1, 'testsuit__testcase__templates__header': "{'Content-Type':'application/json'}", 'testsuit__testcase__templates__data': '{\r\n     "id":"ewr3-deee3-2ewq2-uhue7",\r\n     "params":{\r\n            "name":"{{username}}",\r\n            "passcode":"{{password}}",\r\n            " check":"${check|<{{remember_flag}}>}"\r\n      }\r\n}', 'testsuit__testcase__scenario__scenario': '用户密码均正确', 'testsuit__testcase__scenario__parameter': "[{'password': 'aaaa1111!'}, {'username': 'zhangwenke'}, {'remember_flag': 'true'}]", 'testsuit__testcase__scenario__validator': "[{'code': 200}]"}]}, {'中国外汇交易中心项目': [{'testsuit__module': 'ODM', 'testsuit__class_title': 'ODM交易系统', 'testsuit__testcase__case': 'order_submit', 'testsuit__testcase__case_title': '限价订单提交', 'testsuit__testcase__case_description': None, 'testsuit__testcase__templates__name': '现券XBOND订单提交', 'testsuit__testcase__templates__url': 'https://www.cnblogs.com/aaronthon/ajax/GetPostStat', 'testsuit__testcase__templates__method': 1, 'testsuit__testcase__templates__header': '{"content-type": "application/json", "Authorization":"9480295ab2e2eddb8"}', 'testsuit__testcase__templates__data': '{\r\n    "ordrData": {\r\n      "clntQtCd": "",\r\n      "stlmntSpdNm": 2,\r\n      "cntngncyIndctr": null,\r\n      "flxblNetPrc": null,\r\n      "qtTp": "${login}|<{{username}},{{password}}>",\r\n      "netPrc": "{{netPrc}}",\r\n      "instnCd": "{{instnCd}}",\r\n      "nmnlVol": "{{volumn}}",\r\n      "ordrTpIndctr": "1"\r\n  }\r\n}', 'testsuit__testcase__scenario__scenario': '限价订单提交-T+1', 'testsuit__testcase__scenario__parameter': "[{'netPrc': '100.2344'}, {'password': 'aaaa1111!'}, {'instnCd': '100035'}, {'volumn': '1000,000'}, {'username': 'zhangwneke'}]", 'testsuit__testcase__scenario__validator': "[{'code': 200}, {'result': ' sussess'}]"}]}]
[2021-08-09 17:09:44] [DEBUG] 汇总后的全部项目信息为：[{'上海证券交易所': [{'KMS': [{'case': 'login_kms', 'case_title': 'KMS用户登录接口', 'case_description': 'KMS用户登录接口', 'templates__name': 'kms登录模板', 'url': 'http://119.123.2.1:8980/login', 'method': 1, 'header': {'Content-Type': 'application/json'}, 'data': {'id': 'ewr3-deee3-2ewq2-uhue7', 'params': {'name': '{{username}}', 'passcode': '{{password}}', ' check': '${check|<{{remember_flag}}>}'}}, 'scenarios': [{'parameter': [{'password': ' sdad@1332'}, {'username': 'zhangwenke'}, {'remember_flag': 'true'}], 'name': '用户正确密码错误', 'validator': [{'code': 200}]}, {'parameter': [{'password': 'aaaa1111!'}, {'username': 'zhangwenke'}, {'remember_flag': 'true'}], 'name': '用户密码均正确', 'validator': [{'code': 200}]}]}]}]}, {'中国外汇交易中心项目': [{'ODM': [{'case': 'order_submit', 'case_title': '限价订单提交', 'case_description': None, 'templates__name': '现券XBOND订单提交', 'url': 'https://www.cnblogs.com/aaronthon/ajax/GetPostStat', 'method': 1, 'header': {'content-type': 'application/json', 'Authorization': '9480295ab2e2eddb8'}, 'data': {'ordrData': {'clntQtCd': '', 'stlmntSpdNm': 2, 'cntngncyIndctr': '', 'flxblNetPrc': '', 'qtTp': '${login}|<{{username}},{{password}}>', 'netPrc': '{{netPrc}}', 'instnCd': '{{instnCd}}', 'nmnlVol': '{{volumn}}', 'ordrTpIndctr': '1'}}, 'scenarios': [{'parameter': [{'netPrc': '100.2344'}, {'password': 'aaaa1111!'}, {'instnCd': '100035'}, {'volumn': '1000,000'}, {'username': 'zhangwneke'}], 'name': '限价订单提交-T+1', 'validator': [{'code': 200}, {'result': ' sussess'}]}]}]}]}]
[2021-08-09 17:09:47] [DEBUG] Start to match permission: <class 'tuple'>
[2021-08-09 17:09:47] [DEBUG] The logined user is:{request.user,} and the current url is: {current_url_name}
[2021-08-09 17:09:47] [DEBUG] The permission list is: {permission_list}
[2021-08-09 17:09:47] [DEBUG] The permission group is: <QuerySet [('web_table_data',), ('web_table_update_view',), ('web_table_update',), ('web_table_add',), ('web_table_add_view',), ('web_table_delete_view',), ('password_reset_get',)]>
[2021-08-09 17:09:47] [DEBUG] The matched result is: [True, True, True]
[2021-08-09 17:09:47] [DEBUG] The permission name is: web_table_data and permissions are:[True, True, True]
[2021-08-09 17:09:47] [INFO] Splite the permission: f('web', 'table', 'data')
[2021-08-09 17:09:47] [DEBUG] Create permission: {perm_obj}
[2021-08-09 17:09:47] [INFO] The user have the permission!
[2021-08-09 17:09:47] [DEBUG] Prepare to execute: delete_selected!
[2021-08-09 17:09:47] [DEBUG] Prepare to execute: valid_selected!
[2021-08-09 17:09:47] [DEBUG] Prepare to execute: invalid_selected!
[2021-08-09 17:09:47] [ERROR] Fail to display the field :[check_template]
[2021-08-09 17:09:47] [ERROR] Fail to display the field :[check_template]
[2021-08-09 17:09:47] [DEBUG] The user have access: <HttpResponse status_code=200, "text/html; charset=utf-8"> to get the page!
[2021-08-09 17:09:47] [DEBUG] Prepare to execute: delete_selected!
[2021-08-09 17:09:47] [DEBUG] Prepare to execute: valid_selected!
[2021-08-09 17:09:47] [DEBUG] Prepare to execute: invalid_selected!
[2021-08-09 17:09:47] [ERROR] Fail to display the field :[check_template]
[2021-08-09 17:09:47] [ERROR] Fail to display the field :[check_template]
[2021-08-09 17:10:00] [DEBUG] 修剪后的全部项目信息:[{'上海证券交易所': [{'testsuit__module': 'KMS', 'testsuit__class_title': 'KMS系统', 'testsuit__testcase__case': 'login_kms', 'testsuit__testcase__case_title': 'KMS用户登录接口', 'testsuit__testcase__case_description': 'KMS用户登录接口', 'testsuit__testcase__templates__name': 'kms登录模板', 'testsuit__testcase__templates__url': 'http://119.123.2.1:8980/login', 'testsuit__testcase__templates__method': 1, 'testsuit__testcase__templates__header': "{'Content-Type':'application/json'}", 'testsuit__testcase__templates__data': '{\r\n     "id":"ewr3-deee3-2ewq2-uhue7",\r\n     "params":{\r\n            "name":"{{username}}",\r\n            "passcode":"{{password}}",\r\n            " check":"${check|<{{remember_flag}}>}"\r\n      }\r\n}', 'testsuit__testcase__scenario__scenario': '用户正确密码错误', 'testsuit__testcase__scenario__parameter': "[{'password': ' sdad@1332'}, {'username': 'zhangwenke'}, {'remember_flag': 'true'}]", 'testsuit__testcase__scenario__validator': "[{'code': 200}]"}, {'testsuit__module': 'KMS', 'testsuit__class_title': 'KMS系统', 'testsuit__testcase__case': 'login_kms', 'testsuit__testcase__case_title': 'KMS用户登录接口', 'testsuit__testcase__case_description': 'KMS用户登录接口', 'testsuit__testcase__templates__name': 'kms登录模板', 'testsuit__testcase__templates__url': 'http://119.123.2.1:8980/login', 'testsuit__testcase__templates__method': 1, 'testsuit__testcase__templates__header': "{'Content-Type':'application/json'}", 'testsuit__testcase__templates__data': '{\r\n     "id":"ewr3-deee3-2ewq2-uhue7",\r\n     "params":{\r\n            "name":"{{username}}",\r\n            "passcode":"{{password}}",\r\n            " check":"${check|<{{remember_flag}}>}"\r\n      }\r\n}', 'testsuit__testcase__scenario__scenario': '用户密码均正确', 'testsuit__testcase__scenario__parameter': "[{'password': 'aaaa1111!'}, {'username': 'zhangwenke'}, {'remember_flag': 'true'}]", 'testsuit__testcase__scenario__validator': "[{'code': 200}]"}]}, {'中国外汇交易中心项目': [{'testsuit__module': 'ODM', 'testsuit__class_title': 'ODM交易系统', 'testsuit__testcase__case': 'order_submit', 'testsuit__testcase__case_title': '限价订单提交', 'testsuit__testcase__case_description': None, 'testsuit__testcase__templates__name': '现券XBOND订单提交', 'testsuit__testcase__templates__url': 'https://www.cnblogs.com/aaronthon/ajax/GetPostStat', 'testsuit__testcase__templates__method': 1, 'testsuit__testcase__templates__header': '{"content-type": "application/json", "Authorization":"9480295ab2e2eddb8"}', 'testsuit__testcase__templates__data': '{\r\n    "ordrData": {\r\n      "clntQtCd": "",\r\n      "stlmntSpdNm": 2,\r\n      "cntngncyIndctr": null,\r\n      "flxblNetPrc": null,\r\n      "qtTp": "${login}|<{{username}},{{password}}>",\r\n      "netPrc": "{{netPrc}}",\r\n      "instnCd": "{{instnCd}}",\r\n      "nmnlVol": "{{volumn}}",\r\n      "ordrTpIndctr": "1"\r\n  }\r\n}', 'testsuit__testcase__scenario__scenario': '限价订单提交-T+1', 'testsuit__testcase__scenario__parameter': "[{'netPrc': '100.2344'}, {'password': 'aaaa1111!'}, {'instnCd': '100035'}, {'volumn': '1000,000'}, {'username': 'zhangwneke'}]", 'testsuit__testcase__scenario__validator': "[{'code': 200}, {'result': ' sussess'}]"}]}]
[2021-08-09 17:10:00] [DEBUG] 汇总后的全部项目信息为：[{'上海证券交易所': [{'KMS': [{'case': 'login_kms', 'case_title': 'KMS用户登录接口', 'case_description': 'KMS用户登录接口', 'templates__name': 'kms登录模板', 'url': 'http://119.123.2.1:8980/login', 'method': 1, 'header': {'Content-Type': 'application/json'}, 'data': {'id': 'ewr3-deee3-2ewq2-uhue7', 'params': {'name': '{{username}}', 'passcode': '{{password}}', ' check': '${check|<{{remember_flag}}>}'}}, 'scenarios': [{'parameter': [{'password': ' sdad@1332'}, {'username': 'zhangwenke'}, {'remember_flag': 'true'}], 'name': '用户正确密码错误', 'validator': [{'code': 200}]}, {'parameter': [{'password': 'aaaa1111!'}, {'username': 'zhangwenke'}, {'remember_flag': 'true'}], 'name': '用户密码均正确', 'validator': [{'code': 200}]}]}]}]}, {'中国外汇交易中心项目': [{'ODM': [{'case': 'order_submit', 'case_title': '限价订单提交', 'case_description': None, 'templates__name': '现券XBOND订单提交', 'url': 'https://www.cnblogs.com/aaronthon/ajax/GetPostStat', 'method': 1, 'header': {'content-type': 'application/json', 'Authorization': '9480295ab2e2eddb8'}, 'data': {'ordrData': {'clntQtCd': '', 'stlmntSpdNm': 2, 'cntngncyIndctr': '', 'flxblNetPrc': '', 'qtTp': '${login}|<{{username}},{{password}}>', 'netPrc': '{{netPrc}}', 'instnCd': '{{instnCd}}', 'nmnlVol': '{{volumn}}', 'ordrTpIndctr': '1'}}, 'scenarios': [{'parameter': [{'netPrc': '100.2344'}, {'password': 'aaaa1111!'}, {'instnCd': '100035'}, {'volumn': '1000,000'}, {'username': 'zhangwneke'}], 'name': '限价订单提交-T+1', 'validator': [{'code': 200}, {'result': ' sussess'}]}]}]}]}]
[2021-08-09 17:10:02] [DEBUG] Start to match permission: <class 'tuple'>
[2021-08-09 17:10:02] [DEBUG] The logined user is:{request.user,} and the current url is: {current_url_name}
[2021-08-09 17:10:02] [DEBUG] The permission list is: {permission_list}
[2021-08-09 17:10:02] [DEBUG] The permission group is: <QuerySet [('web_table_data',), ('web_table_update_view',), ('web_table_update',), ('web_table_add',), ('web_table_add_view',), ('web_table_delete_view',), ('password_reset_get',)]>
[2021-08-09 17:10:02] [DEBUG] The matched result is: [True, True, True]
[2021-08-09 17:10:02] [DEBUG] The permission name is: web_table_data and permissions are:[True, True, True]
[2021-08-09 17:10:02] [INFO] Splite the permission: f('web', 'table', 'data')
[2021-08-09 17:10:02] [DEBUG] Create permission: {perm_obj}
[2021-08-09 17:10:02] [INFO] The user have the permission!
[2021-08-09 17:10:02] [DEBUG] Prepare to execute: delete_selected!
[2021-08-09 17:10:02] [DEBUG] Prepare to execute: valid_selected!
[2021-08-09 17:10:02] [DEBUG] Prepare to execute: invalid_selected!
[2021-08-09 17:10:02] [DEBUG] Prepare to execute: model_actions!
[2021-08-09 17:10:02] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:10:02] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:10:02] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:10:02] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:10:02] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:10:02] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:10:02] [DEBUG] The user have access: <HttpResponse status_code=200, "text/html; charset=utf-8"> to get the page!
[2021-08-09 17:10:02] [DEBUG] Prepare to execute: delete_selected!
[2021-08-09 17:10:02] [DEBUG] Prepare to execute: valid_selected!
[2021-08-09 17:10:02] [DEBUG] Prepare to execute: invalid_selected!
[2021-08-09 17:10:02] [DEBUG] Prepare to execute: model_actions!
[2021-08-09 17:10:02] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:10:02] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:10:02] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:10:02] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:10:02] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:10:02] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:22:36] [ERROR] Fail to import application: [django.contrib.admin],due to error: No module named 'django.contrib.admin.api_admin'
[2021-08-09 17:22:36] [ERROR] Fail to import application: [django.contrib.auth],due to error: No module named 'django.contrib.auth.api_admin'
[2021-08-09 17:22:36] [ERROR] Fail to import application: [django.contrib.contenttypes],due to error: No module named 'django.contrib.contenttypes.api_admin'
[2021-08-09 17:22:36] [ERROR] Fail to import application: [django.contrib.sessions],due to error: No module named 'django.contrib.sessions.api_admin'
[2021-08-09 17:22:36] [ERROR] Fail to import application: [django.contrib.messages],due to error: No module named 'django.contrib.messages.api_admin'
[2021-08-09 17:22:36] [ERROR] Fail to import application: [django.contrib.staticfiles],due to error: No module named 'django.contrib.staticfiles.api_admin'
[2021-08-09 17:22:36] [DEBUG] The application and model name are [('api', 'apiproject')]
[2021-08-09 17:22:36] [DEBUG] The application and model name are [('api', 'templates')]
[2021-08-09 17:22:36] [DEBUG] The application and model name are [('api', 'testsuit')]
[2021-08-09 17:22:36] [DEBUG] The application and model name are [('api', 'testcase')]
[2021-08-09 17:22:36] [DEBUG] The application and model name are [('api', 'scenario')]
[2021-08-09 17:22:36] [DEBUG] The application and model name are [('api', 'sql')]
[2021-08-09 17:22:36] [DEBUG] Success to import application :[api]
[2021-08-09 17:22:36] [ERROR] Fail to import application: [backend],due to error: No module named 'backend.api_admin'
[2021-08-09 17:22:36] [ERROR] Fail to import application: [public],due to error: No module named 'public.api_admin'
[2021-08-09 17:22:36] [ERROR] Fail to import application: [django.contrib.admin],due to error: No module named 'django.contrib.admin.public_admin'
[2021-08-09 17:22:36] [ERROR] Fail to import application: [django.contrib.auth],due to error: No module named 'django.contrib.auth.public_admin'
[2021-08-09 17:22:36] [ERROR] Fail to import application: [django.contrib.contenttypes],due to error: No module named 'django.contrib.contenttypes.public_admin'
[2021-08-09 17:22:36] [ERROR] Fail to import application: [django.contrib.sessions],due to error: No module named 'django.contrib.sessions.public_admin'
[2021-08-09 17:22:36] [ERROR] Fail to import application: [django.contrib.messages],due to error: No module named 'django.contrib.messages.public_admin'
[2021-08-09 17:22:36] [ERROR] Fail to import application: [django.contrib.staticfiles],due to error: No module named 'django.contrib.staticfiles.public_admin'
[2021-08-09 17:22:36] [ERROR] Fail to import application: [api],due to error: No module named 'api.public_admin'
[2021-08-09 17:22:36] [ERROR] Fail to import application: [backend],due to error: No module named 'backend.public_admin'
[2021-08-09 17:22:36] [DEBUG] The application and model name are [('public', 'userprofile')]
[2021-08-09 17:22:36] [DEBUG] The application and model name are [('public', 'groups')]
[2021-08-09 17:22:36] [DEBUG] The application and model name are [('public', 'role')]
[2021-08-09 17:22:36] [DEBUG] The application and model name are [('public', 'firstlayermenu')]
[2021-08-09 17:22:36] [DEBUG] The application and model name are [('public', 'submenu')]
[2021-08-09 17:22:36] [DEBUG] The application and model name are [('public', 'businessfunc')]
[2021-08-09 17:22:36] [DEBUG] The application and model name are [('public', 'retrieval')]
[2021-08-09 17:22:36] [DEBUG] The application and model name are [('public', 'resource')]
[2021-08-09 17:22:36] [DEBUG] The application and model name are [('public', 'environment')]
[2021-08-09 17:22:36] [DEBUG] The application and model name are [('public', 'dbinfo')]
[2021-08-09 17:22:36] [DEBUG] The application and model name are [('public', 'logserverinfo')]
[2021-08-09 17:22:36] [DEBUG] The application and model name are [('public', 'configurations')]
[2021-08-09 17:22:36] [DEBUG] The application and model name are [('public', 'cn_en_map')]
[2021-08-09 17:22:36] [DEBUG] The application and model name are [('public', 'steplog')]
[2021-08-09 17:22:36] [DEBUG] The application and model name are [('public', 'todolist')]
[2021-08-09 17:22:36] [DEBUG] Success to import application :[public]
[2021-08-09 17:22:36] [ERROR] Fail to import application: [django.contrib.admin],due to error: No module named 'django.contrib.admin.api_admin'
[2021-08-09 17:22:36] [ERROR] Fail to import application: [django.contrib.auth],due to error: No module named 'django.contrib.auth.api_admin'
[2021-08-09 17:22:36] [ERROR] Fail to import application: [django.contrib.contenttypes],due to error: No module named 'django.contrib.contenttypes.api_admin'
[2021-08-09 17:22:36] [ERROR] Fail to import application: [django.contrib.sessions],due to error: No module named 'django.contrib.sessions.api_admin'
[2021-08-09 17:22:36] [ERROR] Fail to import application: [django.contrib.messages],due to error: No module named 'django.contrib.messages.api_admin'
[2021-08-09 17:22:36] [ERROR] Fail to import application: [django.contrib.staticfiles],due to error: No module named 'django.contrib.staticfiles.api_admin'
[2021-08-09 17:22:36] [DEBUG] Success to import application :[api]
[2021-08-09 17:22:36] [ERROR] Fail to import application: [backend],due to error: No module named 'backend.api_admin'
[2021-08-09 17:22:36] [ERROR] Fail to import application: [public],due to error: No module named 'public.api_admin'
[2021-08-09 17:22:36] [ERROR] Fail to import application: [django.contrib.admin],due to error: No module named 'django.contrib.admin.web_admin'
[2021-08-09 17:22:36] [ERROR] Fail to import application: [django.contrib.auth],due to error: No module named 'django.contrib.auth.web_admin'
[2021-08-09 17:22:36] [ERROR] Fail to import application: [django.contrib.contenttypes],due to error: No module named 'django.contrib.contenttypes.web_admin'
[2021-08-09 17:22:36] [ERROR] Fail to import application: [django.contrib.sessions],due to error: No module named 'django.contrib.sessions.web_admin'
[2021-08-09 17:22:36] [ERROR] Fail to import application: [django.contrib.messages],due to error: No module named 'django.contrib.messages.web_admin'
[2021-08-09 17:22:36] [ERROR] Fail to import application: [django.contrib.staticfiles],due to error: No module named 'django.contrib.staticfiles.web_admin'
[2021-08-09 17:22:36] [ERROR] Fail to import application: [api],due to error: No module named 'api.web_admin'
[2021-08-09 17:22:36] [ERROR] Fail to import application: [backend],due to error: No module named 'backend.web_admin'
[2021-08-09 17:22:36] [ERROR] Fail to import application: [public],due to error: No module named 'public.web_admin'
[2021-08-09 17:22:54] [ERROR] Fail to import application: [django.contrib.admin],due to error: No module named 'django.contrib.admin.api_admin'
[2021-08-09 17:22:54] [ERROR] Fail to import application: [django.contrib.auth],due to error: No module named 'django.contrib.auth.api_admin'
[2021-08-09 17:22:54] [ERROR] Fail to import application: [django.contrib.contenttypes],due to error: No module named 'django.contrib.contenttypes.api_admin'
[2021-08-09 17:22:54] [ERROR] Fail to import application: [django.contrib.sessions],due to error: No module named 'django.contrib.sessions.api_admin'
[2021-08-09 17:22:54] [ERROR] Fail to import application: [django.contrib.messages],due to error: No module named 'django.contrib.messages.api_admin'
[2021-08-09 17:22:54] [ERROR] Fail to import application: [django.contrib.staticfiles],due to error: No module named 'django.contrib.staticfiles.api_admin'
[2021-08-09 17:22:54] [DEBUG] The application and model name are [('api', 'apiproject')]
[2021-08-09 17:22:54] [DEBUG] The application and model name are [('api', 'templates')]
[2021-08-09 17:22:54] [DEBUG] The application and model name are [('api', 'testsuit')]
[2021-08-09 17:22:54] [DEBUG] The application and model name are [('api', 'testcase')]
[2021-08-09 17:22:54] [DEBUG] The application and model name are [('api', 'scenario')]
[2021-08-09 17:22:54] [DEBUG] The application and model name are [('api', 'sql')]
[2021-08-09 17:22:54] [DEBUG] Success to import application :[api]
[2021-08-09 17:22:54] [ERROR] Fail to import application: [backend],due to error: No module named 'backend.api_admin'
[2021-08-09 17:22:54] [ERROR] Fail to import application: [public],due to error: No module named 'public.api_admin'
[2021-08-09 17:22:54] [ERROR] Fail to import application: [django.contrib.admin],due to error: No module named 'django.contrib.admin.public_admin'
[2021-08-09 17:22:54] [ERROR] Fail to import application: [django.contrib.auth],due to error: No module named 'django.contrib.auth.public_admin'
[2021-08-09 17:22:54] [ERROR] Fail to import application: [django.contrib.contenttypes],due to error: No module named 'django.contrib.contenttypes.public_admin'
[2021-08-09 17:22:54] [ERROR] Fail to import application: [django.contrib.sessions],due to error: No module named 'django.contrib.sessions.public_admin'
[2021-08-09 17:22:54] [ERROR] Fail to import application: [django.contrib.messages],due to error: No module named 'django.contrib.messages.public_admin'
[2021-08-09 17:22:54] [ERROR] Fail to import application: [django.contrib.staticfiles],due to error: No module named 'django.contrib.staticfiles.public_admin'
[2021-08-09 17:22:54] [ERROR] Fail to import application: [api],due to error: No module named 'api.public_admin'
[2021-08-09 17:22:54] [ERROR] Fail to import application: [backend],due to error: No module named 'backend.public_admin'
[2021-08-09 17:22:54] [DEBUG] The application and model name are [('public', 'userprofile')]
[2021-08-09 17:22:54] [DEBUG] The application and model name are [('public', 'groups')]
[2021-08-09 17:22:54] [DEBUG] The application and model name are [('public', 'role')]
[2021-08-09 17:22:54] [DEBUG] The application and model name are [('public', 'firstlayermenu')]
[2021-08-09 17:22:54] [DEBUG] The application and model name are [('public', 'submenu')]
[2021-08-09 17:22:54] [DEBUG] The application and model name are [('public', 'businessfunc')]
[2021-08-09 17:22:54] [DEBUG] The application and model name are [('public', 'retrieval')]
[2021-08-09 17:22:54] [DEBUG] The application and model name are [('public', 'resource')]
[2021-08-09 17:22:54] [DEBUG] The application and model name are [('public', 'environment')]
[2021-08-09 17:22:54] [DEBUG] The application and model name are [('public', 'dbinfo')]
[2021-08-09 17:22:54] [DEBUG] The application and model name are [('public', 'logserverinfo')]
[2021-08-09 17:22:54] [DEBUG] The application and model name are [('public', 'configurations')]
[2021-08-09 17:22:54] [DEBUG] The application and model name are [('public', 'cn_en_map')]
[2021-08-09 17:22:54] [DEBUG] The application and model name are [('public', 'steplog')]
[2021-08-09 17:22:54] [DEBUG] The application and model name are [('public', 'todolist')]
[2021-08-09 17:22:54] [DEBUG] Success to import application :[public]
[2021-08-09 17:22:54] [ERROR] Fail to import application: [django.contrib.admin],due to error: No module named 'django.contrib.admin.api_admin'
[2021-08-09 17:22:54] [ERROR] Fail to import application: [django.contrib.auth],due to error: No module named 'django.contrib.auth.api_admin'
[2021-08-09 17:22:54] [ERROR] Fail to import application: [django.contrib.contenttypes],due to error: No module named 'django.contrib.contenttypes.api_admin'
[2021-08-09 17:22:54] [ERROR] Fail to import application: [django.contrib.sessions],due to error: No module named 'django.contrib.sessions.api_admin'
[2021-08-09 17:22:54] [ERROR] Fail to import application: [django.contrib.messages],due to error: No module named 'django.contrib.messages.api_admin'
[2021-08-09 17:22:54] [ERROR] Fail to import application: [django.contrib.staticfiles],due to error: No module named 'django.contrib.staticfiles.api_admin'
[2021-08-09 17:22:54] [DEBUG] Success to import application :[api]
[2021-08-09 17:22:54] [ERROR] Fail to import application: [backend],due to error: No module named 'backend.api_admin'
[2021-08-09 17:22:54] [ERROR] Fail to import application: [public],due to error: No module named 'public.api_admin'
[2021-08-09 17:22:54] [ERROR] Fail to import application: [django.contrib.admin],due to error: No module named 'django.contrib.admin.web_admin'
[2021-08-09 17:22:54] [ERROR] Fail to import application: [django.contrib.auth],due to error: No module named 'django.contrib.auth.web_admin'
[2021-08-09 17:22:54] [ERROR] Fail to import application: [django.contrib.contenttypes],due to error: No module named 'django.contrib.contenttypes.web_admin'
[2021-08-09 17:22:54] [ERROR] Fail to import application: [django.contrib.sessions],due to error: No module named 'django.contrib.sessions.web_admin'
[2021-08-09 17:22:54] [ERROR] Fail to import application: [django.contrib.messages],due to error: No module named 'django.contrib.messages.web_admin'
[2021-08-09 17:22:54] [ERROR] Fail to import application: [django.contrib.staticfiles],due to error: No module named 'django.contrib.staticfiles.web_admin'
[2021-08-09 17:22:54] [ERROR] Fail to import application: [api],due to error: No module named 'api.web_admin'
[2021-08-09 17:22:54] [ERROR] Fail to import application: [backend],due to error: No module named 'backend.web_admin'
[2021-08-09 17:22:54] [ERROR] Fail to import application: [public],due to error: No module named 'public.web_admin'
[2021-08-09 17:23:28] [ERROR] Fail to import application: [django.contrib.admin],due to error: No module named 'django.contrib.admin.api_admin'
[2021-08-09 17:23:28] [ERROR] Fail to import application: [django.contrib.auth],due to error: No module named 'django.contrib.auth.api_admin'
[2021-08-09 17:23:28] [ERROR] Fail to import application: [django.contrib.contenttypes],due to error: No module named 'django.contrib.contenttypes.api_admin'
[2021-08-09 17:23:28] [ERROR] Fail to import application: [django.contrib.sessions],due to error: No module named 'django.contrib.sessions.api_admin'
[2021-08-09 17:23:28] [ERROR] Fail to import application: [django.contrib.messages],due to error: No module named 'django.contrib.messages.api_admin'
[2021-08-09 17:23:28] [ERROR] Fail to import application: [django.contrib.staticfiles],due to error: No module named 'django.contrib.staticfiles.api_admin'
[2021-08-09 17:23:28] [DEBUG] The application and model name are [('api', 'apiproject')]
[2021-08-09 17:23:28] [DEBUG] The application and model name are [('api', 'templates')]
[2021-08-09 17:23:28] [DEBUG] The application and model name are [('api', 'testsuit')]
[2021-08-09 17:23:28] [DEBUG] The application and model name are [('api', 'testcase')]
[2021-08-09 17:23:28] [DEBUG] The application and model name are [('api', 'scenario')]
[2021-08-09 17:23:28] [DEBUG] The application and model name are [('api', 'sql')]
[2021-08-09 17:23:28] [DEBUG] Success to import application :[api]
[2021-08-09 17:23:28] [ERROR] Fail to import application: [backend],due to error: No module named 'backend.api_admin'
[2021-08-09 17:23:28] [ERROR] Fail to import application: [public],due to error: No module named 'public.api_admin'
[2021-08-09 17:23:28] [ERROR] Fail to import application: [django.contrib.admin],due to error: No module named 'django.contrib.admin.public_admin'
[2021-08-09 17:23:28] [ERROR] Fail to import application: [django.contrib.auth],due to error: No module named 'django.contrib.auth.public_admin'
[2021-08-09 17:23:28] [ERROR] Fail to import application: [django.contrib.contenttypes],due to error: No module named 'django.contrib.contenttypes.public_admin'
[2021-08-09 17:23:28] [ERROR] Fail to import application: [django.contrib.sessions],due to error: No module named 'django.contrib.sessions.public_admin'
[2021-08-09 17:23:28] [ERROR] Fail to import application: [django.contrib.messages],due to error: No module named 'django.contrib.messages.public_admin'
[2021-08-09 17:23:28] [ERROR] Fail to import application: [django.contrib.staticfiles],due to error: No module named 'django.contrib.staticfiles.public_admin'
[2021-08-09 17:23:28] [ERROR] Fail to import application: [api],due to error: No module named 'api.public_admin'
[2021-08-09 17:23:28] [ERROR] Fail to import application: [backend],due to error: No module named 'backend.public_admin'
[2021-08-09 17:23:28] [DEBUG] The application and model name are [('public', 'userprofile')]
[2021-08-09 17:23:28] [DEBUG] The application and model name are [('public', 'groups')]
[2021-08-09 17:23:28] [DEBUG] The application and model name are [('public', 'role')]
[2021-08-09 17:23:28] [DEBUG] The application and model name are [('public', 'firstlayermenu')]
[2021-08-09 17:23:28] [DEBUG] The application and model name are [('public', 'submenu')]
[2021-08-09 17:23:28] [DEBUG] The application and model name are [('public', 'businessfunc')]
[2021-08-09 17:23:28] [DEBUG] The application and model name are [('public', 'retrieval')]
[2021-08-09 17:23:28] [DEBUG] The application and model name are [('public', 'resource')]
[2021-08-09 17:23:28] [DEBUG] The application and model name are [('public', 'environment')]
[2021-08-09 17:23:28] [DEBUG] The application and model name are [('public', 'dbinfo')]
[2021-08-09 17:23:28] [DEBUG] The application and model name are [('public', 'logserverinfo')]
[2021-08-09 17:23:28] [DEBUG] The application and model name are [('public', 'configurations')]
[2021-08-09 17:23:28] [DEBUG] The application and model name are [('public', 'cn_en_map')]
[2021-08-09 17:23:28] [DEBUG] The application and model name are [('public', 'steplog')]
[2021-08-09 17:23:28] [DEBUG] The application and model name are [('public', 'todolist')]
[2021-08-09 17:23:28] [DEBUG] Success to import application :[public]
[2021-08-09 17:23:28] [ERROR] Fail to import application: [django.contrib.admin],due to error: No module named 'django.contrib.admin.api_admin'
[2021-08-09 17:23:28] [ERROR] Fail to import application: [django.contrib.auth],due to error: No module named 'django.contrib.auth.api_admin'
[2021-08-09 17:23:28] [ERROR] Fail to import application: [django.contrib.contenttypes],due to error: No module named 'django.contrib.contenttypes.api_admin'
[2021-08-09 17:23:28] [ERROR] Fail to import application: [django.contrib.sessions],due to error: No module named 'django.contrib.sessions.api_admin'
[2021-08-09 17:23:28] [ERROR] Fail to import application: [django.contrib.messages],due to error: No module named 'django.contrib.messages.api_admin'
[2021-08-09 17:23:28] [ERROR] Fail to import application: [django.contrib.staticfiles],due to error: No module named 'django.contrib.staticfiles.api_admin'
[2021-08-09 17:23:28] [DEBUG] Success to import application :[api]
[2021-08-09 17:23:28] [ERROR] Fail to import application: [backend],due to error: No module named 'backend.api_admin'
[2021-08-09 17:23:28] [ERROR] Fail to import application: [public],due to error: No module named 'public.api_admin'
[2021-08-09 17:23:28] [ERROR] Fail to import application: [django.contrib.admin],due to error: No module named 'django.contrib.admin.web_admin'
[2021-08-09 17:23:28] [ERROR] Fail to import application: [django.contrib.auth],due to error: No module named 'django.contrib.auth.web_admin'
[2021-08-09 17:23:28] [ERROR] Fail to import application: [django.contrib.contenttypes],due to error: No module named 'django.contrib.contenttypes.web_admin'
[2021-08-09 17:23:28] [ERROR] Fail to import application: [django.contrib.sessions],due to error: No module named 'django.contrib.sessions.web_admin'
[2021-08-09 17:23:28] [ERROR] Fail to import application: [django.contrib.messages],due to error: No module named 'django.contrib.messages.web_admin'
[2021-08-09 17:23:28] [ERROR] Fail to import application: [django.contrib.staticfiles],due to error: No module named 'django.contrib.staticfiles.web_admin'
[2021-08-09 17:23:28] [ERROR] Fail to import application: [api],due to error: No module named 'api.web_admin'
[2021-08-09 17:23:28] [ERROR] Fail to import application: [backend],due to error: No module named 'backend.web_admin'
[2021-08-09 17:23:28] [ERROR] Fail to import application: [public],due to error: No module named 'public.web_admin'
[2021-08-09 17:24:39] [ERROR] Fail to import application: [django.contrib.admin],due to error: No module named 'django.contrib.admin.api_admin'
[2021-08-09 17:24:39] [ERROR] Fail to import application: [django.contrib.auth],due to error: No module named 'django.contrib.auth.api_admin'
[2021-08-09 17:24:39] [ERROR] Fail to import application: [django.contrib.contenttypes],due to error: No module named 'django.contrib.contenttypes.api_admin'
[2021-08-09 17:24:39] [ERROR] Fail to import application: [django.contrib.sessions],due to error: No module named 'django.contrib.sessions.api_admin'
[2021-08-09 17:24:39] [ERROR] Fail to import application: [django.contrib.messages],due to error: No module named 'django.contrib.messages.api_admin'
[2021-08-09 17:24:39] [ERROR] Fail to import application: [django.contrib.staticfiles],due to error: No module named 'django.contrib.staticfiles.api_admin'
[2021-08-09 17:24:39] [DEBUG] The application and model name are [('api', 'apiproject')]
[2021-08-09 17:24:39] [DEBUG] The application and model name are [('api', 'templates')]
[2021-08-09 17:24:39] [DEBUG] The application and model name are [('api', 'testsuit')]
[2021-08-09 17:24:39] [DEBUG] The application and model name are [('api', 'testcase')]
[2021-08-09 17:24:39] [DEBUG] The application and model name are [('api', 'scenario')]
[2021-08-09 17:24:39] [DEBUG] The application and model name are [('api', 'sql')]
[2021-08-09 17:24:39] [DEBUG] Success to import application :[api]
[2021-08-09 17:24:39] [ERROR] Fail to import application: [backend],due to error: No module named 'backend.api_admin'
[2021-08-09 17:24:39] [ERROR] Fail to import application: [public],due to error: No module named 'public.api_admin'
[2021-08-09 17:24:39] [ERROR] Fail to import application: [django.contrib.admin],due to error: No module named 'django.contrib.admin.public_admin'
[2021-08-09 17:24:39] [ERROR] Fail to import application: [django.contrib.auth],due to error: No module named 'django.contrib.auth.public_admin'
[2021-08-09 17:24:39] [ERROR] Fail to import application: [django.contrib.contenttypes],due to error: No module named 'django.contrib.contenttypes.public_admin'
[2021-08-09 17:24:39] [ERROR] Fail to import application: [django.contrib.sessions],due to error: No module named 'django.contrib.sessions.public_admin'
[2021-08-09 17:24:39] [ERROR] Fail to import application: [django.contrib.messages],due to error: No module named 'django.contrib.messages.public_admin'
[2021-08-09 17:24:39] [ERROR] Fail to import application: [django.contrib.staticfiles],due to error: No module named 'django.contrib.staticfiles.public_admin'
[2021-08-09 17:24:39] [ERROR] Fail to import application: [api],due to error: No module named 'api.public_admin'
[2021-08-09 17:24:39] [ERROR] Fail to import application: [backend],due to error: No module named 'backend.public_admin'
[2021-08-09 17:24:39] [DEBUG] The application and model name are [('public', 'userprofile')]
[2021-08-09 17:24:39] [DEBUG] The application and model name are [('public', 'groups')]
[2021-08-09 17:24:39] [DEBUG] The application and model name are [('public', 'role')]
[2021-08-09 17:24:39] [DEBUG] The application and model name are [('public', 'firstlayermenu')]
[2021-08-09 17:24:39] [DEBUG] The application and model name are [('public', 'submenu')]
[2021-08-09 17:24:39] [DEBUG] The application and model name are [('public', 'businessfunc')]
[2021-08-09 17:24:39] [DEBUG] The application and model name are [('public', 'retrieval')]
[2021-08-09 17:24:39] [DEBUG] The application and model name are [('public', 'resource')]
[2021-08-09 17:24:39] [DEBUG] The application and model name are [('public', 'environment')]
[2021-08-09 17:24:39] [DEBUG] The application and model name are [('public', 'dbinfo')]
[2021-08-09 17:24:39] [DEBUG] The application and model name are [('public', 'logserverinfo')]
[2021-08-09 17:24:39] [DEBUG] The application and model name are [('public', 'configurations')]
[2021-08-09 17:24:39] [DEBUG] The application and model name are [('public', 'cn_en_map')]
[2021-08-09 17:24:39] [DEBUG] The application and model name are [('public', 'steplog')]
[2021-08-09 17:24:39] [DEBUG] The application and model name are [('public', 'todolist')]
[2021-08-09 17:24:39] [DEBUG] Success to import application :[public]
[2021-08-09 17:24:39] [ERROR] Fail to import application: [django.contrib.admin],due to error: No module named 'django.contrib.admin.api_admin'
[2021-08-09 17:24:39] [ERROR] Fail to import application: [django.contrib.auth],due to error: No module named 'django.contrib.auth.api_admin'
[2021-08-09 17:24:39] [ERROR] Fail to import application: [django.contrib.contenttypes],due to error: No module named 'django.contrib.contenttypes.api_admin'
[2021-08-09 17:24:39] [ERROR] Fail to import application: [django.contrib.sessions],due to error: No module named 'django.contrib.sessions.api_admin'
[2021-08-09 17:24:39] [ERROR] Fail to import application: [django.contrib.messages],due to error: No module named 'django.contrib.messages.api_admin'
[2021-08-09 17:24:39] [ERROR] Fail to import application: [django.contrib.staticfiles],due to error: No module named 'django.contrib.staticfiles.api_admin'
[2021-08-09 17:24:39] [DEBUG] Success to import application :[api]
[2021-08-09 17:24:39] [ERROR] Fail to import application: [backend],due to error: No module named 'backend.api_admin'
[2021-08-09 17:24:39] [ERROR] Fail to import application: [public],due to error: No module named 'public.api_admin'
[2021-08-09 17:24:39] [ERROR] Fail to import application: [django.contrib.admin],due to error: No module named 'django.contrib.admin.web_admin'
[2021-08-09 17:24:39] [ERROR] Fail to import application: [django.contrib.auth],due to error: No module named 'django.contrib.auth.web_admin'
[2021-08-09 17:24:39] [ERROR] Fail to import application: [django.contrib.contenttypes],due to error: No module named 'django.contrib.contenttypes.web_admin'
[2021-08-09 17:24:39] [ERROR] Fail to import application: [django.contrib.sessions],due to error: No module named 'django.contrib.sessions.web_admin'
[2021-08-09 17:24:39] [ERROR] Fail to import application: [django.contrib.messages],due to error: No module named 'django.contrib.messages.web_admin'
[2021-08-09 17:24:39] [ERROR] Fail to import application: [django.contrib.staticfiles],due to error: No module named 'django.contrib.staticfiles.web_admin'
[2021-08-09 17:24:39] [ERROR] Fail to import application: [api],due to error: No module named 'api.web_admin'
[2021-08-09 17:24:39] [ERROR] Fail to import application: [backend],due to error: No module named 'backend.web_admin'
[2021-08-09 17:24:39] [ERROR] Fail to import application: [public],due to error: No module named 'public.web_admin'
[2021-08-09 17:26:30] [ERROR] Fail to import application: [django.contrib.admin],due to error: No module named 'django.contrib.admin.api_admin'
[2021-08-09 17:26:30] [ERROR] Fail to import application: [django.contrib.auth],due to error: No module named 'django.contrib.auth.api_admin'
[2021-08-09 17:26:30] [ERROR] Fail to import application: [django.contrib.contenttypes],due to error: No module named 'django.contrib.contenttypes.api_admin'
[2021-08-09 17:26:30] [ERROR] Fail to import application: [django.contrib.sessions],due to error: No module named 'django.contrib.sessions.api_admin'
[2021-08-09 17:26:30] [ERROR] Fail to import application: [django.contrib.messages],due to error: No module named 'django.contrib.messages.api_admin'
[2021-08-09 17:26:30] [ERROR] Fail to import application: [django.contrib.staticfiles],due to error: No module named 'django.contrib.staticfiles.api_admin'
[2021-08-09 17:26:30] [DEBUG] The application and model name are [('api', 'apiproject')]
[2021-08-09 17:26:30] [DEBUG] The application and model name are [('api', 'templates')]
[2021-08-09 17:26:30] [DEBUG] The application and model name are [('api', 'testsuit')]
[2021-08-09 17:26:30] [DEBUG] The application and model name are [('api', 'testcase')]
[2021-08-09 17:26:30] [DEBUG] The application and model name are [('api', 'scenario')]
[2021-08-09 17:26:30] [DEBUG] The application and model name are [('api', 'sql')]
[2021-08-09 17:26:30] [DEBUG] Success to import application :[api]
[2021-08-09 17:26:30] [ERROR] Fail to import application: [backend],due to error: No module named 'backend.api_admin'
[2021-08-09 17:26:30] [ERROR] Fail to import application: [public],due to error: No module named 'public.api_admin'
[2021-08-09 17:26:30] [ERROR] Fail to import application: [django.contrib.admin],due to error: No module named 'django.contrib.admin.public_admin'
[2021-08-09 17:26:30] [ERROR] Fail to import application: [django.contrib.auth],due to error: No module named 'django.contrib.auth.public_admin'
[2021-08-09 17:26:30] [ERROR] Fail to import application: [django.contrib.contenttypes],due to error: No module named 'django.contrib.contenttypes.public_admin'
[2021-08-09 17:26:30] [ERROR] Fail to import application: [django.contrib.sessions],due to error: No module named 'django.contrib.sessions.public_admin'
[2021-08-09 17:26:30] [ERROR] Fail to import application: [django.contrib.messages],due to error: No module named 'django.contrib.messages.public_admin'
[2021-08-09 17:26:30] [ERROR] Fail to import application: [django.contrib.staticfiles],due to error: No module named 'django.contrib.staticfiles.public_admin'
[2021-08-09 17:26:30] [ERROR] Fail to import application: [api],due to error: No module named 'api.public_admin'
[2021-08-09 17:26:30] [ERROR] Fail to import application: [backend],due to error: No module named 'backend.public_admin'
[2021-08-09 17:26:30] [DEBUG] The application and model name are [('public', 'userprofile')]
[2021-08-09 17:26:30] [DEBUG] The application and model name are [('public', 'groups')]
[2021-08-09 17:26:30] [DEBUG] The application and model name are [('public', 'role')]
[2021-08-09 17:26:30] [DEBUG] The application and model name are [('public', 'firstlayermenu')]
[2021-08-09 17:26:30] [DEBUG] The application and model name are [('public', 'submenu')]
[2021-08-09 17:26:30] [DEBUG] The application and model name are [('public', 'businessfunc')]
[2021-08-09 17:26:30] [DEBUG] The application and model name are [('public', 'retrieval')]
[2021-08-09 17:26:30] [DEBUG] The application and model name are [('public', 'resource')]
[2021-08-09 17:26:30] [DEBUG] The application and model name are [('public', 'environment')]
[2021-08-09 17:26:30] [DEBUG] The application and model name are [('public', 'dbinfo')]
[2021-08-09 17:26:30] [DEBUG] The application and model name are [('public', 'logserverinfo')]
[2021-08-09 17:26:30] [DEBUG] The application and model name are [('public', 'configurations')]
[2021-08-09 17:26:30] [DEBUG] The application and model name are [('public', 'cn_en_map')]
[2021-08-09 17:26:30] [DEBUG] The application and model name are [('public', 'steplog')]
[2021-08-09 17:26:30] [DEBUG] The application and model name are [('public', 'todolist')]
[2021-08-09 17:26:30] [DEBUG] Success to import application :[public]
[2021-08-09 17:26:30] [ERROR] Fail to import application: [django.contrib.admin],due to error: No module named 'django.contrib.admin.api_admin'
[2021-08-09 17:26:30] [ERROR] Fail to import application: [django.contrib.auth],due to error: No module named 'django.contrib.auth.api_admin'
[2021-08-09 17:26:30] [ERROR] Fail to import application: [django.contrib.contenttypes],due to error: No module named 'django.contrib.contenttypes.api_admin'
[2021-08-09 17:26:30] [ERROR] Fail to import application: [django.contrib.sessions],due to error: No module named 'django.contrib.sessions.api_admin'
[2021-08-09 17:26:30] [ERROR] Fail to import application: [django.contrib.messages],due to error: No module named 'django.contrib.messages.api_admin'
[2021-08-09 17:26:30] [ERROR] Fail to import application: [django.contrib.staticfiles],due to error: No module named 'django.contrib.staticfiles.api_admin'
[2021-08-09 17:26:30] [DEBUG] Success to import application :[api]
[2021-08-09 17:26:30] [ERROR] Fail to import application: [backend],due to error: No module named 'backend.api_admin'
[2021-08-09 17:26:30] [ERROR] Fail to import application: [public],due to error: No module named 'public.api_admin'
[2021-08-09 17:26:30] [ERROR] Fail to import application: [django.contrib.admin],due to error: No module named 'django.contrib.admin.web_admin'
[2021-08-09 17:26:30] [ERROR] Fail to import application: [django.contrib.auth],due to error: No module named 'django.contrib.auth.web_admin'
[2021-08-09 17:26:30] [ERROR] Fail to import application: [django.contrib.contenttypes],due to error: No module named 'django.contrib.contenttypes.web_admin'
[2021-08-09 17:26:30] [ERROR] Fail to import application: [django.contrib.sessions],due to error: No module named 'django.contrib.sessions.web_admin'
[2021-08-09 17:26:30] [ERROR] Fail to import application: [django.contrib.messages],due to error: No module named 'django.contrib.messages.web_admin'
[2021-08-09 17:26:30] [ERROR] Fail to import application: [django.contrib.staticfiles],due to error: No module named 'django.contrib.staticfiles.web_admin'
[2021-08-09 17:26:30] [ERROR] Fail to import application: [api],due to error: No module named 'api.web_admin'
[2021-08-09 17:26:30] [ERROR] Fail to import application: [backend],due to error: No module named 'backend.web_admin'
[2021-08-09 17:26:30] [ERROR] Fail to import application: [public],due to error: No module named 'public.web_admin'
[2021-08-09 17:26:33] [DEBUG] Start to match permission: <class 'tuple'>
[2021-08-09 17:26:33] [DEBUG] The logined user is:{request.user,} and the current url is: {current_url_name}
[2021-08-09 17:26:33] [DEBUG] The permission list is: {permission_list}
[2021-08-09 17:26:33] [DEBUG] The permission group is: <QuerySet [('web_table_data',), ('web_table_update_view',), ('web_table_update',), ('web_table_add',), ('web_table_add_view',), ('web_table_delete_view',), ('password_reset_get',)]>
[2021-08-09 17:26:33] [DEBUG] The matched result is: [True, True, True]
[2021-08-09 17:26:33] [DEBUG] The permission name is: web_table_data and permissions are:[True, True, True]
[2021-08-09 17:26:33] [INFO] Splite the permission: f('web', 'table', 'data')
[2021-08-09 17:26:33] [DEBUG] Create permission: {perm_obj}
[2021-08-09 17:26:33] [INFO] The user have the permission!
[2021-08-09 17:26:33] [DEBUG] Prepare to execute: delete_selected!
[2021-08-09 17:26:33] [DEBUG] Prepare to execute: valid_selected!
[2021-08-09 17:26:33] [DEBUG] Prepare to execute: invalid_selected!
[2021-08-09 17:26:33] [DEBUG] Prepare to execute: model_actions!
[2021-08-09 17:26:33] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:26:33] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:26:33] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:26:33] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:26:33] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:26:33] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:26:33] [DEBUG] The user have access: <HttpResponse status_code=200, "text/html; charset=utf-8"> to get the page!
[2021-08-09 17:26:33] [DEBUG] Prepare to execute: delete_selected!
[2021-08-09 17:26:33] [DEBUG] Prepare to execute: valid_selected!
[2021-08-09 17:26:33] [DEBUG] Prepare to execute: invalid_selected!
[2021-08-09 17:26:33] [DEBUG] Prepare to execute: model_actions!
[2021-08-09 17:26:33] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:26:33] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:26:34] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:26:34] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:26:34] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:26:34] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:26:52] [DEBUG] 修剪后的全部项目信息:[{'上海证券交易所': [{'testsuit__module': 'KMS', 'testsuit__class_title': 'KMS系统', 'testsuit__testcase__case': 'login_kms', 'testsuit__testcase__case_title': 'KMS用户登录接口', 'testsuit__testcase__case_description': 'KMS用户登录接口', 'testsuit__testcase__templates__name': 'kms登录模板', 'testsuit__testcase__templates__url': 'http://119.123.2.1:8980/login', 'testsuit__testcase__templates__method': 1, 'testsuit__testcase__templates__header': "{'Content-Type':'application/json'}", 'testsuit__testcase__templates__data': '{\r\n     "id":"ewr3-deee3-2ewq2-uhue7",\r\n     "params":{\r\n            "name":"{{username}}",\r\n            "passcode":"{{password}}",\r\n            " check":"${check|<{{remember_flag}}>}"\r\n      }\r\n}', 'testsuit__testcase__scenario__scenario': '用户正确密码错误', 'testsuit__testcase__scenario__parameter': "[{'password': ' sdad@1332'}, {'username': 'zhangwenke'}, {'remember_flag': 'true'}]", 'testsuit__testcase__scenario__validator': "[{'code': 200}]"}, {'testsuit__module': 'KMS', 'testsuit__class_title': 'KMS系统', 'testsuit__testcase__case': 'login_kms', 'testsuit__testcase__case_title': 'KMS用户登录接口', 'testsuit__testcase__case_description': 'KMS用户登录接口', 'testsuit__testcase__templates__name': 'kms登录模板', 'testsuit__testcase__templates__url': 'http://119.123.2.1:8980/login', 'testsuit__testcase__templates__method': 1, 'testsuit__testcase__templates__header': "{'Content-Type':'application/json'}", 'testsuit__testcase__templates__data': '{\r\n     "id":"ewr3-deee3-2ewq2-uhue7",\r\n     "params":{\r\n            "name":"{{username}}",\r\n            "passcode":"{{password}}",\r\n            " check":"${check|<{{remember_flag}}>}"\r\n      }\r\n}', 'testsuit__testcase__scenario__scenario': '用户密码均正确', 'testsuit__testcase__scenario__parameter': "[{'password': 'aaaa1111!'}, {'username': 'zhangwenke'}, {'remember_flag': 'true'}]", 'testsuit__testcase__scenario__validator': "[{'code': 200}]"}]}, {'中国外汇交易中心项目': [{'testsuit__module': 'ODM', 'testsuit__class_title': 'ODM交易系统', 'testsuit__testcase__case': 'order_submit', 'testsuit__testcase__case_title': '限价订单提交', 'testsuit__testcase__case_description': None, 'testsuit__testcase__templates__name': '现券XBOND订单提交', 'testsuit__testcase__templates__url': 'https://www.cnblogs.com/aaronthon/ajax/GetPostStat', 'testsuit__testcase__templates__method': 1, 'testsuit__testcase__templates__header': '{"content-type": "application/json", "Authorization":"9480295ab2e2eddb8"}', 'testsuit__testcase__templates__data': '{\r\n    "ordrData": {\r\n      "clntQtCd": "",\r\n      "stlmntSpdNm": 2,\r\n      "cntngncyIndctr": null,\r\n      "flxblNetPrc": null,\r\n      "qtTp": "${login}|<{{username}},{{password}}>",\r\n      "netPrc": "{{netPrc}}",\r\n      "instnCd": "{{instnCd}}",\r\n      "nmnlVol": "{{volumn}}",\r\n      "ordrTpIndctr": "1"\r\n  }\r\n}', 'testsuit__testcase__scenario__scenario': '限价订单提交-T+1', 'testsuit__testcase__scenario__parameter': "[{'netPrc': '100.2344'}, {'password': 'aaaa1111!'}, {'instnCd': '100035'}, {'volumn': '1000,000'}, {'username': 'zhangwneke'}]", 'testsuit__testcase__scenario__validator': "[{'code': 200}, {'result': ' sussess'}]"}]}]
[2021-08-09 17:26:52] [DEBUG] 汇总后的全部项目信息为：[{'上海证券交易所': [{'KMS': [{'case': 'login_kms', 'case_title': 'KMS用户登录接口', 'case_description': 'KMS用户登录接口', 'templates__name': 'kms登录模板', 'url': 'http://119.123.2.1:8980/login', 'method': 1, 'header': {'Content-Type': 'application/json'}, 'data': {'id': 'ewr3-deee3-2ewq2-uhue7', 'params': {'name': '{{username}}', 'passcode': '{{password}}', ' check': '${check|<{{remember_flag}}>}'}}, 'scenarios': [{'parameter': {'password': ' sdad@1332', 'username': 'zhangwenke', 'remember_flag': 'true'}, 'name': '用户正确密码错误', 'validator': {'code': 200}}, {'parameter': {'password': 'aaaa1111!', 'username': 'zhangwenke', 'remember_flag': 'true'}, 'name': '用户密码均正确', 'validator': {'code': 200}}]}]}]}, {'中国外汇交易中心项目': [{'ODM': [{'case': 'order_submit', 'case_title': '限价订单提交', 'case_description': None, 'templates__name': '现券XBOND订单提交', 'url': 'https://www.cnblogs.com/aaronthon/ajax/GetPostStat', 'method': 1, 'header': {'content-type': 'application/json', 'Authorization': '9480295ab2e2eddb8'}, 'data': {'ordrData': {'clntQtCd': '', 'stlmntSpdNm': 2, 'cntngncyIndctr': '', 'flxblNetPrc': '', 'qtTp': '${login}|<{{username}},{{password}}>', 'netPrc': '{{netPrc}}', 'instnCd': '{{instnCd}}', 'nmnlVol': '{{volumn}}', 'ordrTpIndctr': '1'}}, 'scenarios': [{'parameter': {'netPrc': '100.2344', 'password': 'aaaa1111!', 'instnCd': '100035', 'volumn': '1000,000', 'username': 'zhangwneke'}, 'name': '限价订单提交-T+1', 'validator': {'code': 200, 'result': ' sussess'}}]}]}]}]
[2021-08-09 17:42:49] [DEBUG] Start to match permission: <class 'tuple'>
[2021-08-09 17:42:49] [DEBUG] The logined user is:{request.user,} and the current url is: {current_url_name}
[2021-08-09 17:42:49] [DEBUG] The permission list is: {permission_list}
[2021-08-09 17:42:49] [DEBUG] The permission group is: <QuerySet [('web_table_data',), ('web_table_update_view',), ('web_table_update',), ('web_table_add',), ('web_table_add_view',), ('web_table_delete_view',), ('password_reset_get',)]>
[2021-08-09 17:42:49] [DEBUG] The matched result is: [True, True, True]
[2021-08-09 17:42:49] [DEBUG] The permission name is: web_table_data and permissions are:[True, True, True]
[2021-08-09 17:42:49] [INFO] Splite the permission: f('web', 'table', 'data')
[2021-08-09 17:42:49] [DEBUG] Create permission: {perm_obj}
[2021-08-09 17:42:49] [INFO] The user have the permission!
[2021-08-09 17:42:49] [DEBUG] Prepare to execute: delete_selected!
[2021-08-09 17:42:49] [DEBUG] Prepare to execute: valid_selected!
[2021-08-09 17:42:49] [DEBUG] Prepare to execute: invalid_selected!
[2021-08-09 17:42:49] [DEBUG] Prepare to execute: model_actions!
[2021-08-09 17:42:49] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:42:49] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:42:49] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:42:49] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:42:49] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:42:49] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:42:49] [DEBUG] The user have access: <HttpResponse status_code=200, "text/html; charset=utf-8"> to get the page!
[2021-08-09 17:42:49] [DEBUG] Prepare to execute: delete_selected!
[2021-08-09 17:42:49] [DEBUG] Prepare to execute: valid_selected!
[2021-08-09 17:42:49] [DEBUG] Prepare to execute: invalid_selected!
[2021-08-09 17:42:49] [DEBUG] Prepare to execute: model_actions!
[2021-08-09 17:42:49] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:42:49] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:42:49] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:42:49] [ERROR] Fail to display the field :[expand]
[2021-08-09 17:42:49] [ERROR] Fail to display the field :[execute]
[2021-08-09 17:42:49] [ERROR] Fail to display the field :[expand]
[2021-08-10 09:06:59] [DEBUG] 修剪后的全部项目信息:[{'上海证券交易所': [{'testsuit__module': 'KMS', 'testsuit__class_title': 'KMS系统', 'testsuit__testcase__case': 'login_kms', 'testsuit__testcase__case_title': 'KMS用户登录接口', 'testsuit__testcase__case_description': 'KMS用户登录接口', 'testsuit__testcase__templates__name': 'kms登录模板', 'testsuit__testcase__templates__url': 'http://119.123.2.1:8980/login', 'testsuit__testcase__templates__method': 1, 'testsuit__testcase__templates__header': "{'Content-Type':'application/json'}", 'testsuit__testcase__templates__data': '{\r\n     "id":"ewr3-deee3-2ewq2-uhue7",\r\n     "params":{\r\n            "name":"{{username}}",\r\n            "passcode":"{{password}}",\r\n            " check":"${check|<{{remember_flag}}>}"\r\n      }\r\n}', 'testsuit__testcase__scenario__scenario': '用户正确密码错误', 'testsuit__testcase__scenario__parameter': "[{'password': ' sdad@1332'}, {'username': 'zhangwenke'}, {'remember_flag': 'true'}]", 'testsuit__testcase__scenario__validator': "[{'code': 200}]"}, {'testsuit__module': 'KMS', 'testsuit__class_title': 'KMS系统', 'testsuit__testcase__case': 'login_kms', 'testsuit__testcase__case_title': 'KMS用户登录接口', 'testsuit__testcase__case_description': 'KMS用户登录接口', 'testsuit__testcase__templates__name': 'kms登录模板', 'testsuit__testcase__templates__url': 'http://119.123.2.1:8980/login', 'testsuit__testcase__templates__method': 1, 'testsuit__testcase__templates__header': "{'Content-Type':'application/json'}", 'testsuit__testcase__templates__data': '{\r\n     "id":"ewr3-deee3-2ewq2-uhue7",\r\n     "params":{\r\n            "name":"{{username}}",\r\n            "passcode":"{{password}}",\r\n            " check":"${check|<{{remember_flag}}>}"\r\n      }\r\n}', 'testsuit__testcase__scenario__scenario': '用户密码均正确', 'testsuit__testcase__scenario__parameter': "[{'password': 'aaaa1111!'}, {'username': 'zhangwenke'}, {'remember_flag': 'true'}]", 'testsuit__testcase__scenario__validator': "[{'code': 200}]"}]}, {'中国外汇交易中心项目': [{'testsuit__module': 'ODM', 'testsuit__class_title': 'ODM交易系统', 'testsuit__testcase__case': 'order_submit', 'testsuit__testcase__case_title': '限价订单提交', 'testsuit__testcase__case_description': None, 'testsuit__testcase__templates__name': '现券XBOND订单提交', 'testsuit__testcase__templates__url': 'https://www.cnblogs.com/aaronthon/ajax/GetPostStat', 'testsuit__testcase__templates__method': 1, 'testsuit__testcase__templates__header': '{"content-type": "application/json", "Authorization":"9480295ab2e2eddb8"}', 'testsuit__testcase__templates__data': '{\r\n    "ordrData": {\r\n      "clntQtCd": "",\r\n      "stlmntSpdNm": 2,\r\n      "cntngncyIndctr": null,\r\n      "flxblNetPrc": null,\r\n      "qtTp": "${login}|<{{username}},{{password}}>",\r\n      "netPrc": "{{netPrc}}",\r\n      "instnCd": "{{instnCd}}",\r\n      "nmnlVol": "{{volumn}}",\r\n      "ordrTpIndctr": "1"\r\n  }\r\n}', 'testsuit__testcase__scenario__scenario': '限价订单提交-T+1', 'testsuit__testcase__scenario__parameter': "[{'netPrc': '100.2344'}, {'password': 'aaaa1111!'}, {'instnCd': '100035'}, {'volumn': '1000,000'}, {'username': 'zhangwneke'}]", 'testsuit__testcase__scenario__validator': "[{'code': 200}, {'result': ' sussess'}]"}]}]
[2021-08-10 09:06:59] [DEBUG] 汇总后的全部项目信息为：[{'上海证券交易所': [{'KMS': [{'case': 'login_kms', 'case_title': 'KMS用户登录接口', 'case_description': 'KMS用户登录接口', 'templates__name': 'kms登录模板', 'url': 'http://119.123.2.1:8980/login', 'method': 1, 'header': {'Content-Type': 'application/json'}, 'data': {'id': 'ewr3-deee3-2ewq2-uhue7', 'params': {'name': '{{username}}', 'passcode': '{{password}}', ' check': '${check|<{{remember_flag}}>}'}}, 'scenarios': [{'parameter': {'password': ' sdad@1332', 'username': 'zhangwenke', 'remember_flag': 'true'}, 'name': '用户正确密码错误', 'validator': {'code': 200}}, {'parameter': {'password': 'aaaa1111!', 'username': 'zhangwenke', 'remember_flag': 'true'}, 'name': '用户密码均正确', 'validator': {'code': 200}}]}]}]}, {'中国外汇交易中心项目': [{'ODM': [{'case': 'order_submit', 'case_title': '限价订单提交', 'case_description': None, 'templates__name': '现券XBOND订单提交', 'url': 'https://www.cnblogs.com/aaronthon/ajax/GetPostStat', 'method': 1, 'header': {'content-type': 'application/json', 'Authorization': '9480295ab2e2eddb8'}, 'data': {'ordrData': {'clntQtCd': '', 'stlmntSpdNm': 2, 'cntngncyIndctr': '', 'flxblNetPrc': '', 'qtTp': '${login}|<{{username}},{{password}}>', 'netPrc': '{{netPrc}}', 'instnCd': '{{instnCd}}', 'nmnlVol': '{{volumn}}', 'ordrTpIndctr': '1'}}, 'scenarios': [{'parameter': {'netPrc': '100.2344', 'password': 'aaaa1111!', 'instnCd': '100035', 'volumn': '1000,000', 'username': 'zhangwneke'}, 'name': '限价订单提交-T+1', 'validator': {'code': 200, 'result': ' sussess'}}]}]}]}]
[2021-08-10 09:07:01] [DEBUG] Start to match permission: <class 'tuple'>
[2021-08-10 09:07:01] [DEBUG] The logined user is:{request.user,} and the current url is: {current_url_name}
[2021-08-10 09:07:01] [DEBUG] The permission list is: {permission_list}
[2021-08-10 09:07:01] [DEBUG] The permission group is: <QuerySet [('web_table_data',), ('web_table_update_view',), ('web_table_update',), ('web_table_add',), ('web_table_add_view',), ('web_table_delete_view',), ('password_reset_get',)]>
[2021-08-10 09:07:01] [DEBUG] The matched result is: [True, True, True]
[2021-08-10 09:07:01] [DEBUG] The permission name is: web_table_data and permissions are:[True, True, True]
[2021-08-10 09:07:01] [INFO] Splite the permission: f('web', 'table', 'data')
[2021-08-10 09:07:01] [DEBUG] Create permission: {perm_obj}
[2021-08-10 09:07:01] [INFO] The user have the permission!
[2021-08-10 09:07:02] [DEBUG] Prepare to execute: delete_selected!
[2021-08-10 09:07:02] [DEBUG] Prepare to execute: valid_selected!
[2021-08-10 09:07:02] [DEBUG] Prepare to execute: invalid_selected!
[2021-08-10 09:07:02] [ERROR] Fail to display the field :[execute]
[2021-08-10 09:07:02] [ERROR] Fail to display the field :[expand]
[2021-08-10 09:07:02] [ERROR] Fail to display the field :[execute]
[2021-08-10 09:07:02] [ERROR] Fail to display the field :[expand]
[2021-08-10 09:07:02] [DEBUG] The user have access: <HttpResponse status_code=200, "text/html; charset=utf-8"> to get the page!
[2021-08-10 09:07:02] [DEBUG] Prepare to execute: delete_selected!
[2021-08-10 09:07:02] [DEBUG] Prepare to execute: valid_selected!
[2021-08-10 09:07:02] [DEBUG] Prepare to execute: invalid_selected!
[2021-08-10 09:07:02] [ERROR] Fail to display the field :[execute]
[2021-08-10 09:07:02] [ERROR] Fail to display the field :[expand]
[2021-08-10 09:07:02] [ERROR] Fail to display the field :[execute]
[2021-08-10 09:07:02] [ERROR] Fail to display the field :[expand]
